// deno-lint-ignore-file no-import-prefix
/**
 * Regenerates the parser artifacts — pure ESM TypeScript parsers — from the
 * in-repo jison grammars (`sparql.jison`, `turtle.jison`).
 *
 * The SPARQL half mirrors sparqljs@3.7.4's own build step:
 *   jison lib/sparql.jison -p slr -m js -o lib/SparqlParser.js
 *   echo 'module.exports=SparqlParser' >> lib/SparqlParser.js
 *
 * Prior art: the generated parsers are table-driven LR (SLR) parsers built
 * from a context-free grammar — the classic compiler-construction
 * technique of Aho, Sethi & Ullman (the grammar itself is sparqljs 3.7.4's
 * jison grammar; see README.md).
 * @see Aho, Sethi & Ullman, "Compilers: Principles, Techniques, and Tools," Addison-Wesley, 1986, ch. 4 (syntax analysis, LR parsing)
 *
 * then post-processes the output into ESM/TS:
 *
 *   - inlines `Wildcard` (upstream `lib/Wildcard.js`) so the generated SPARQL
 *     module has no `require` and the file can be deleted,
 *   - replaces `module.exports=<ModuleName>` with a default ESM export,
 *   - prepends `// @ts-nocheck` and `// deno-lint-ignore-file` so the files
 *     need no `deno.json` fmt/lint excludes (they are generated code),
 *   - runs `deno fmt` so the checked-in artifacts are fmt-stable and
 *     regenerating reproduces them byte-for-byte.
 *
 * Run via `deno task parser:generate`. With `--check`, it verifies instead of
 * writing: it exits non-zero when a checked-in artifact has drifted from its
 * grammar (used by `deno task parser:check` in CI).
 */
import jison from "npm:jison@0.4.18";
import { parse as parseGrammar } from "npm:ebnf-parser@0.1.10";

// jison@0.4.18 and ebnf-parser@0.1.10 ship no TypeScript types, so their
// surfaces are typed `any` here (guarded by the generation diff in CI).
type JisonModule = {
  Generator: new (
    grammar: Record<string, unknown>,
    options: Record<string, unknown>,
  ) => { generate: (options: Record<string, unknown>) => string };
};
type EbnfParser = { parse: (grammar: string) => Record<string, unknown> };

/** A (grammar, output artifact) pair generated by `deno task parser:generate`. */
interface ParserTarget {
  grammarPath: URL;
  outputPath: URL;
  moduleName: string;
  /** Human-readable label used in logs and the generated-file header. */
  label: string;
}

const TARGETS: ParserTarget[] = [
  {
    grammarPath: new URL("./sparql.jison", import.meta.url),
    outputPath: new URL("./parser.ts", import.meta.url),
    moduleName: "SparqlParser",
    label: "parser.ts",
  },
  {
    grammarPath: new URL("./turtle.jison", import.meta.url),
    outputPath: new URL("./turtle-generated.ts", import.meta.url),
    moduleName: "TurtleParser",
    label: "turtle-generated.ts",
  },
];

/**
 * wildcardSource is upstream `lib/Wildcard.js` (sparqljs@3.7.4) with the
 * `module.exports` line removed, inlined so the generated SPARQL parser has no
 * `require` and `Wildcard.js` can be deleted from the tree. The Turtle parser
 * never emits this `require`, so the replacement is a no-op for it.
 */
const WILDCARD_SOURCE = `
// Wildcard singleton (inlined from sparqljs@3.7.4 lib/Wildcard.js)
class Wildcard {
  constructor() {
    return WILDCARD || this;
  }

  equals(other) {
    return other && (this.termType === other.termType);
  }
}

Object.defineProperty(Wildcard.prototype, 'value', {
  enumerable: true,
  value: '*',
});

Object.defineProperty(Wildcard.prototype, 'termType', {
  enumerable: true,
  value: 'Wildcard',
});

var WILDCARD = new Wildcard();
`;

/** Generates the ESM/TS parser source for the given grammar text (no I/O). */
export function generateParserSource(
  rawGrammar: string,
  moduleName: string,
): string {
  const grammar = (parseGrammar as unknown as EbnfParser["parse"])(rawGrammar);
  const generator = new (jison as unknown as JisonModule).Generator(grammar, {
    type: "slr",
    moduleType: "js",
    moduleName,
    debug: false,
  });
  const source = generator.generate({
    type: "slr",
    moduleType: "js",
    moduleName,
    debug: false,
  });

  // sparqljs's build appends the CommonJS export line to jison's raw output;
  // append the ESM default export the maintained wrappers import instead.
  const esm = source.replace(
    "var Wildcard = require('./Wildcard').Wildcard;",
    WILDCARD_SOURCE,
  );

  // Generated code is not hand-maintained: skip type checking and linting so
  // deno.json needs no excludes for these files.
  return (
    "// @ts-nocheck\n" +
    "// deno-lint-ignore-file\n" +
    `// Generated by \`deno task parser:generate\` — edit the .jison grammar instead.\n` +
    esm +
    `export default ${moduleName};\n`
  );
}

/**
 * formatWithDenoFmt formats a source string with the project's `deno fmt`
 * rules (via a throwaway temp file), so the checked-in artifacts are
 * fmt-stable and regeneration reproduces them byte-for-byte.
 */
async function formatWithDenoFmt(source: string): Promise<string> {
  // The temp file lives in the OS temp dir (not the repo, where a crashed run
  // would leak it into fmt:check and git status), and fileURLToPath is unused:
  // Deno.makeTempFile already returns a platform-native path (URL.pathname is
  // a POSIX-style `/C:/...` string that the Windows CLI mangles).
  const tempPath = await Deno.makeTempFile({
    prefix: "parser-fmt-",
    suffix: ".ts",
  });
  await Deno.writeTextFile(tempPath, source);
  try {
    const cmd = new Deno.Command(Deno.execPath(), {
      args: ["fmt", tempPath],
    });
    const { code, stderr } = await cmd.output();
    if (code !== 0) {
      throw new Error(
        `deno fmt failed: ${new TextDecoder().decode(stderr)}`,
      );
    }
    return await Deno.readTextFile(tempPath);
  } finally {
    await Deno.remove(tempPath);
  }
}

async function main(): Promise<void> {
  const checkOnly = Deno.args.includes("--check");
  let allOk = true;

  for (const target of TARGETS) {
    const rawGrammar = await Deno.readTextFile(target.grammarPath);
    const formatted = await formatWithDenoFmt(
      generateParserSource(rawGrammar, target.moduleName),
    );

    if (checkOnly) {
      const current = await Deno.readTextFile(target.outputPath);
      if (current !== formatted) {
        console.error(
          `${target.label} is out of date with ${
            target.grammarPath.pathname
              .split("/")
              .pop()
          }. ` +
            "Run `deno task parser:generate` and commit the result.",
        );
        allOk = false;
      } else {
        console.log(`${target.label} is up to date with its grammar.`);
      }
    } else {
      await Deno.writeTextFile(target.outputPath, formatted);
      console.log(`Generated ${target.label} (${formatted.length} bytes)`);
    }
  }

  if (checkOnly && !allOk) {
    Deno.exit(1);
  }
}

if (import.meta.main) {
  await main();
}
