%{
  /*
    Turtle / TriG / N-Triples / N-Quads parser in the Jison parser generator
    format — RDF 1.2, maintained by this project.

    Generated by `deno task parser:generate`; the runtime artifact
    (`turtle-generated.ts`) is pure ESM with zero runtime dependencies — term
    construction goes through the injected DataFactory (Parser.factory).

    The grammar mirrors the W3C RDF 1.2 TriG grammar (a superset of Turtle
    that also accepts N-Triples), extended with an N-Quads-style graph label
    on top-level statements so LOAD can ingest database-dump documents. The
    RDF 1.2 surface (triple terms, reifiers, annotation blocks) follows the
    spec's state-machine parsing semantics (TriG 5.3): reifiers and
    annotations emit `reifier rdf:reifies <<( s p o )>>` triples, and the
    node produced by a reified triple `<< s p o >>` is its reifier.
  */

  // State lives on statics so the generated module has no imports of its own:
  //   Parser.factory   — RDF/JS DataFactory (injected by the wrapper)
  //   Parser.base      — current base IRI (mutated by @base / BASE)
  //   Parser.prefixes  — { prefix: namespace } map (mutated by @prefix / PREFIX)
  //   Parser.quads     — output Quad[] (reset per parse)
  //   Parser._state    — { graph, subject, predicate, object, reifier,
  //                        tripleTerm, bnodeCounter, collectionStack,
  //                        pending, savedSubject, savedPredicate }

  var RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
      RDF_TYPE = RDF + 'type',
      RDF_FIRST = RDF + 'first',
      RDF_REST = RDF + 'rest',
      RDF_NIL = RDF + 'nil',
      RDF_REIFIES = RDF + 'reifies',
      XSD = 'http://www.w3.org/2001/XMLSchema#',
      XSD_INTEGER = XSD + 'integer',
      XSD_DECIMAL = XSD + 'decimal',
      XSD_DOUBLE = XSD + 'double',
      XSD_BOOLEAN = XSD + 'boolean';

  function state() { return Parser._state; }

  function graphTerm() { return state().graph || Parser.factory.defaultGraph(); }

  // Quads are buffered per statement and flushed by finishStatement so the
  // N-Quads graph label (which appears after the object list) can set the
  // graph before the quads are emitted.
  function emitQuad(s, p, o) { state().pending.push([s, p, o]); }

  function finishStatement() {
    var st = state();
    var g = graphTerm();
    for (var i = 0; i < st.pending.length; i++) {
      var q = st.pending[i];
      Parser.quads.push(Parser.factory.quad(q[0], q[1], q[2], g));
    }
    st.pending = [];
  }

  function freshBnode() {
    return Parser.factory.blankNode('b' + (++state().bnodeCounter));
  }

  function resolveIri(iri) {
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(iri)) return iri;
    if (!Parser.base) return iri;
    try {
      return new URL(iri, Parser.base).href;
    } catch (e) {
      return Parser.base + iri;
    }
  }

  function decodeUchar(m, u4, u8) {
    var cp = parseInt(u4 || u8, 16);
    if (cp >= 0xD800 && cp <= 0xDFFF) {
      throw new Error('Invalid Unicode escape (surrogate code point): ' + m);
    }
    return String.fromCodePoint(cp);
  }

  function unescapeString(raw) {
    var quotes = /^'''|^\"\"\"|^'|^\"/.exec(raw)[0];
    var body = raw.slice(quotes.length, raw.length - quotes.length);
    return body
      .replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar)
      .replace(/\\([tbnrf"'\\])/g, function (m, ch) {
        return { t: '\t', b: '\b', n: '\n', r: '\r', f: '\f', '"': '"', "'": "'", '\\': '\\' }[ch];
      });
  }

  function unescapeIri(iri) {
    var result = iri.replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar);
    // IRIREF excludes U+0000-U+0020 and <>"{}|^`\\; an escape must not
    // smuggle any of them into the decoded IRI.
    if (/[\u0000-\u0020<>"{}|^`\\]/.test(result)) {
      throw new Error('Invalid IRI escape: disallowed character');
    }
    return result;
  }

  function resolvePrefixed(tok) {
    var i = tok.indexOf(':');
    var prefix = tok.slice(0, i);
    var ns = Parser.prefixes[prefix];
    if (ns == null) {
      throw new Error('Undefined prefix: ' + prefix + ':');
    }
    // PN_LOCAL_ESC sequences (\_ \~ \. \- \! \$ \& \' \( \) \* \+ \, \; \= \/ \? \# \@ \%)
    // denote the literal character (TriG 4.5 PN_LOCAL_ESC); percent-escapes are kept as-is.
    return ns + tok.slice(i + 1).replace(/\\([_~.\-!$&'()*+,;=/?#@%])/g, '$1');
  }

  function addPrefix(pnameNs, iriTok) {
    var prefix = pnameNs.slice(0, -1);
    Parser.prefixes[prefix] = resolveIri(iriTok.slice(1, -1));
  }

  // --- RDF 1.2 reifier / annotation state machine (TriG 5.3.4-5.3.7) ---

  function startAnnotation() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.tripleTerm = Parser.factory.quad(st.subject, st.predicate, st.object);
    st.reifier = undefined;
  }

  function endAnnotation() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
  }

  function startAnnotationBlock() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    st.subject = st.reifier;
  }

  function endAnnotationBlock() {
    state().reifier = undefined;
  }

  function applyReifier(reifierTerm) {
    var st = state();
    st.reifier = reifierTerm || freshBnode();
    emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
  }

  // Finishing a reified triple (TriG 5.3.5): if no `~ reifier` was matched,
  // assign a fresh blank node; the reifying triple was already emitted by the
  // reifier production when a reifier was present. The node produced by the
  // production is the reifier.
  function nn(value) { return Parser.factory.namedNode(value); }

  function finishReifiedTriple() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    var node = st.reifier;
    st.reifier = undefined;
    return node;
  }

  // Emits the triple for a parsed object and prepares the annotation context
  // (TriG 5.3.3 / 5.3.6). Returns the object value.
  function emitObject(o) {
    state().object = o;
    emitQuad(state().subject, state().predicate, o);
    startAnnotation();
    return o;
  }

  // --- blank node property lists (TriG 5.3.8) ---

  function startBnpl() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.bnplNode = freshBnode();
    st.subject = st.bnplNode;
  }

  function endBnpl() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    return st.bnplNode;
  }

  // --- collections (TriG 5.3.9) ---

  function startCollection() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.collectionStack.push({ items: [] });
  }

  function collectionAdd(item) {
    state().collectionStack[state().collectionStack.length - 1].items.push(item);
  }

  function endCollection() {
    var st = state();
    var coll = st.collectionStack.pop();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    var items = coll.items;
    if (items.length === 0) {
      return Parser.factory.namedNode(RDF_NIL);
    }
    var head = freshBnode();
    var cur = head;
    for (var i = 0; i < items.length; i++) {
      emitQuad(cur, nn(RDF_FIRST), items[i]);
      if (i < items.length - 1) {
        var next = freshBnode();
        emitQuad(cur, nn(RDF_REST), next);
        cur = next;
      } else {
        emitQuad(cur, nn(RDF_REST), nn(RDF_NIL));
      }
    }
    return head;
  }
%}

%lex

// Terminal regexes — W3C RDF 1.2 TriG section 4.5 (productions for terminals).
HEX           [0-9A-Fa-f]
UCHAR         "\\u"{HEX}{HEX}{HEX}{HEX}|"\\U"{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}
ECHAR         "\\"[tbnrf"'\\]
PN_CHARS_BASE [A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]
PN_CHARS_U    ({PN_CHARS_BASE}|"_")
PN_CHARS      ({PN_CHARS_U}|"-"|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])
PN_PREFIX     ({PN_CHARS_BASE})(({PN_CHARS}|".")*{PN_CHARS})?
PN_LOCAL      ({PN_CHARS_U}|":"|[0-9]|{PLX})(({PN_CHARS}|"."|":"|{PLX})*({PN_CHARS}|":"|{PLX}))?
PLX           ({PERCENT}|{PN_LOCAL_ESC})
PERCENT       "%"[0-9A-Fa-f]{2}
PN_LOCAL_ESC  "\\"("_"|"~"|"."|"-"|"!"|"$"|"&"|"'"|"("|")"|"*"|"+"|","|";"|"="|"/"|"?"|"#"|"@"|"%")
PNAME_NS      ({PN_PREFIX}?":")
PNAME_LN      ({PNAME_NS}{PN_LOCAL})
BLANK_NODE_LABEL "_:"({PN_CHARS_U}|[0-9])(({PN_CHARS}|".")*{PN_CHARS})?
IRIREF        "<"(?:[^<>\"{}|^`\\\u0000-\u0020]|{UCHAR})*">"
LANG_DIR      "@"[a-zA-Z]+("-"[a-zA-Z0-9]+)*("--"("ltr"|"rtl"))?
INTEGER       [+-]?[0-9]+
DECIMAL       [+-]?([0-9]*"."[0-9]+)
DOUBLE        [+-]?(([0-9]+"."[0-9]*{EXPONENT})|("."[0-9]+{EXPONENT})|([0-9]+{EXPONENT}))
EXPONENT      [eE][+-]?[0-9]+
STRING_LITERAL_LONG_QUOTE        "\"\"\""((("\""|"\"\"")?([^"\\]|{ECHAR}|{UCHAR}))*)"\"\"\""
STRING_LITERAL_LONG_SINGLE_QUOTE "'''"((("'"|"''")?([^'\\]|{ECHAR}|{UCHAR}))*)"'''"
STRING_LITERAL_QUOTE             "\""([^\u0022\u005C\u000A\u000D]|{ECHAR}|{UCHAR})*"\""
STRING_LITERAL_SINGLE_QUOTE      "'"([^\u0027\u005C\u000A\u000D]|{ECHAR}|{UCHAR})*"'"
ANON          "["\s*"]"
COMMENT       "#"[^\n\r]*

%options flex

%%

\s+|{COMMENT}                  /* ignore */
"@prefix"                      return 'PREFIX_ID'
"@base"                        return 'BASE_ID'
"@version"                     return 'VERSION_ID'
[Pp][Rr][Ee][Ff][Ii][Xx]       return 'SPARQL_PREFIX'
[Bb][Aa][Ss][Ee]               return 'SPARQL_BASE'
[Vv][Ee][Rr][Ss][Ii][Oo][Nn]   return 'SPARQL_VERSION'
"GRAPH"                        return 'GRAPH'
"a"                            return 'a'
"true"|"false"                 return 'BOOLEAN'
"^^"                           return '^^'
"<<("                          return '<<('
")>>"                          return ')>>'
"<<"                           return '<<'
">>"                           return '>>'
"~"                            return '~'
"{|"                           return '{|'
"|}"                           return '|}'
"."                            return '.'
";"                            return ';'
","                            return ','
"("                            return '('
")"                            return ')'
"["                            return '['
"]"                            return ']'
"{"                            return '{'
"}"                            return '}'
{ANON}                         return 'ANON'
{IRIREF}                       return 'IRIREF'
{PNAME_LN}                     return 'PNAME_LN'
{PNAME_NS}                     return 'PNAME_NS'
{BLANK_NODE_LABEL}             return 'BLANK_NODE_LABEL'
{LANG_DIR}                     return 'LANG_DIR'
{STRING_LITERAL_LONG_QUOTE}    return 'STRING_LONG'
{STRING_LITERAL_LONG_SINGLE_QUOTE} return 'STRING_LONG'
{STRING_LITERAL_QUOTE}         return 'STRING'
{STRING_LITERAL_SINGLE_QUOTE}  return 'STRING'
{DOUBLE}                       return 'DOUBLE'
{DECIMAL}                      return 'DECIMAL'
{INTEGER}                      return 'INTEGER'
.                              return 'INVALID'
/lex

%%

document
  : (directive | block)*
  ;

directive
  : PREFIX_ID PNAME_NS IRIREF "." -> addPrefix($2, $3)
  | SPARQL_PREFIX PNAME_NS IRIREF -> addPrefix($2, $3)
  | BASE_ID IRIREF "."            -> (Parser.base = resolveIri($2.slice(1, -1)))
  | SPARQL_BASE IRIREF            -> (Parser.base = resolveIri($2.slice(1, -1)))
  | VERSION_ID STRING "."         
  | SPARQL_VERSION STRING         
  ;

block
  : triplesOrGraph
  | wrappedGraph
  | triples2
  | GRAPH graphLabelHeader wrappedGraph -> (state().graph = undefined)
  ;

// labelOrSubject in subject position: record it as the statement subject and
// reset the graph to the default (TriG 5.3.1).
subjectHeader
  : labelOrSubject -> (state().subject = $1, state().graph = undefined)
  ;

// labelOrSubject in graph-label position: record it as the current graph.
graphLabelHeader
  : labelOrSubject -> (state().graph = $1)
  ;

// N-Quads-style graph label on a top-level statement (after the object list).
setGraphLabel
  : iri -> (state().graph = $1)
  | BLANK_NODE_LABEL -> (state().graph = Parser.factory.blankNode($1.slice(2)))
  ;

// A reified triple used as a statement subject: its node (the reifier) becomes
// the subject for the following predicate-object list (TriG 5.3.5).
reifiedSubject
  : reifiedTriple -> (state().subject = $1)
  ;

// A blank node property list used as a statement subject: its node becomes the
// subject for the following predicate-object list (TriG 5.3.8). The bare
// blankNodePropertyList production restores the enclosing subject/predicate, so
// we capture the node here before any outer predicate-object list runs.
bnplSubject
  : blankNodePropertyList -> (state().subject = $1)
  ;

triplesOrGraph
  : graphLabelHeader wrappedGraph -> (state().graph = undefined)
  | subjectHeader predicateObjectList "." -> finishStatement()
  | subjectHeader predicateObjectList setGraphLabel "." -> (finishStatement(), state().graph = undefined)
  | reifiedSubject predicateObjectList? "." -> finishStatement()
  ;

triples2
  : bnplSubject predicateObjectList? "." -> finishStatement()
  | collectionSubject predicateObjectList "." -> finishStatement()
  ;

collectionSubject
  : collection -> (state().subject = $1)
  ;

wrappedGraph
  : "{" triplesBlock? "}"
  ;

// A triple statement inside a graph block: flush its buffered quads into the
// current graph when the statement completes (before '.' or '}').
triplesStatement
  : triples -> finishStatement()
  ;

triplesBlock
  : triplesStatement ("." triplesBlock?)?
  ;

labelOrSubject
  : iri -> $1
  | BlankNode -> $1
  ;

triples
  : subject predicateObjectList
  | bnplSubject predicateObjectList?
  | reifiedSubject predicateObjectList?
  ;

subject
  : iri -> (state().subject = $1)
  | BlankNode -> (state().subject = $1)
  | collection -> (state().subject = $1)
  ;

predicateObjectList
  : verb objectList
  | predicateObjectList ";" verb objectList
  | predicateObjectList ";"
  ;

objectList
  : objectEmission annotation -> endAnnotation()
  | objectList "," objectEmission annotation -> endAnnotation()
  ;

// The object production with its triple emission and the annotation start
// (TriG 5.3.3 and 5.3.6): the object value is recorded, the triple
// curSubject curPredicate object is emitted, and the annotation context
// (tripleTerm, saved subject/predicate, cleared reifier) is prepared.
objectEmission
  : object -> emitObject($1)
  ;

verb
  : predicate -> (state().predicate = $1)
  | "a" -> (state().predicate = Parser.factory.namedNode(RDF_TYPE))
  ;

predicate
  : iri -> $1
  ;

object
  : iri -> $1
  | BlankNode -> $1
  | collection -> $1
  | blankNodePropertyList -> $1
  | literal -> $1
  | tripleTerm -> $1
  | reifiedTriple -> $1
  ;

literal
  : RDFLiteral -> $1
  | NumericLiteral -> $1
  | BooleanLiteral -> $1
  ;

RDFLiteral
  : STRING -> Parser.factory.literal(unescapeString($1))
  | STRING_LONG -> Parser.factory.literal(unescapeString($1))
  | STRING LANG_DIR -> Parser.factory.literal(unescapeString($1), $2.slice(1))
  | STRING_LONG LANG_DIR -> Parser.factory.literal(unescapeString($1), $2.slice(1))
  | STRING "^^" iri -> Parser.factory.literal(unescapeString($1), $3)
  | STRING_LONG "^^" iri -> Parser.factory.literal(unescapeString($1), $3)
  ;

NumericLiteral
  : INTEGER -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_INTEGER))
  | DECIMAL -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_DECIMAL))
  | DOUBLE -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_DOUBLE))
  ;

BooleanLiteral
  : BOOLEAN -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_BOOLEAN))
  ;

bnplStart
  : "[" -> startBnpl()
  ;

blankNodePropertyList
  : bnplStart predicateObjectList "]" -> endBnpl()
  ;

collectionStart
  : "(" -> startCollection()
  ;

collection
  : collectionStart ")" -> endCollection()
  | collectionStart collectionItems ")" -> endCollection()
  ;

collectionItems
  : object -> collectionAdd($1)
  | collectionItems object -> collectionAdd($2)
  ;

iri
  : IRIREF -> Parser.factory.namedNode(resolveIri(unescapeIri($1.slice(1, -1))))
  | PNAME_LN -> Parser.factory.namedNode(resolvePrefixed($1))
  | PNAME_NS -> Parser.factory.namedNode(resolvePrefixed($1))
  ;

PrefixedName
  : PNAME_LN -> $1
  | PNAME_NS -> $1
  ;

BlankNode
  : BLANK_NODE_LABEL -> Parser.factory.blankNode($1.slice(2))
  | ANON -> freshBnode()
  ;

tripleTerm
  : "<<(" ttSubject verb ttObject ")>>" -> Parser.factory.quad($2, $3, $4)
  ;

ttSubject
  : iri -> $1
  | BlankNode -> $1
  ;

ttObject
  : iri -> $1
  | BlankNode -> $1
  | literal -> $1
  | tripleTerm -> $1
  ;

// The subject-verb-object body of a reified triple; records the triple term
// before the optional reifier so `~ r` can emit the reifying triple
// (TriG 5.3.4).
reifiedTripleBody
  : rtSubject verb rtObject -> (state().tripleTerm = Parser.factory.quad($1, $2, $3))
  ;

reifiedTriple
  : "<<" reifiedTripleBody reifier? ">>" -> finishReifiedTriple()
  ;

rtSubject
  : iri -> $1
  | BlankNode -> $1
  | reifiedTriple -> $1
  ;

rtObject
  : iri -> $1
  | BlankNode -> $1
  | literal -> $1
  | tripleTerm -> $1
  | reifiedTriple -> $1
  ;

reifier
  : "~" -> applyReifier(undefined)
  | "~" iri -> applyReifier($2)
  | "~" BlankNode -> applyReifier($2)
  ;

annotation
  : annotationPart*
  ;

annotationPart
  : reifier
  | annotationBlock
  ;

annotationBlockStart
  : "{|" -> startAnnotationBlock()
  ;

annotationBlock
  : annotationBlockStart predicateObjectList "|}" -> endAnnotationBlock()
  ;
