%{
  /*
    Turtle / TriG / N-Triples / N-Quads parser in the Jison parser generator
    format — RDF 1.2, maintained by this project.

    Generated by `deno task parser:generate`; the runtime artifact
    (`turtle-generated.ts`) is pure ESM with zero runtime dependencies — term
    construction goes through the injected DataFactory (Parser.factory).

    The grammar mirrors the W3C RDF 1.2 TriG grammar (a superset of Turtle
    that also accepts N-Triples), extended with an N-Quads-style graph label
    on top-level statements so LOAD can ingest database-dump documents. The
    RDF 1.2 surface (triple terms, reifiers, annotation blocks) follows the
    spec's state-machine parsing semantics (TriG 5.3): reifiers and
    annotations emit `reifier rdf:reifies <<( s p o )>>` triples, and the
    node produced by a reified triple `<< s p o >>` is its reifier.
  */

  // State lives on statics so the generated module has no imports of its own:
  //   Parser.factory   — RDF/JS DataFactory (injected by the wrapper)
  //   Parser.base      — current base IRI (mutated by @base / BASE)
  //   Parser.prefixes  — { prefix: namespace } map (mutated by @prefix / PREFIX)
  //   Parser.quads     — output Quad[] (reset per parse)
  //   Parser._state    — { graph, subject, predicate, object, reifier,
  //                        tripleTerm, bnodeCounter, collectionStack,
  //                        pending, savedSubject, savedPredicate }

  var RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
      RDF_TYPE = RDF + 'type',
      RDF_FIRST = RDF + 'first',
      RDF_REST = RDF + 'rest',
      RDF_NIL = RDF + 'nil',
      RDF_REIFIES = RDF + 'reifies',
      RDF_LANGSTRING = RDF + 'langString',
      RDF_DIRLANGSTRING = RDF + 'dirLangString',
      XSD = 'http://www.w3.org/2001/XMLSchema#',
      XSD_INTEGER = XSD + 'integer',
      XSD_DECIMAL = XSD + 'decimal',
      XSD_DOUBLE = XSD + 'double',
      XSD_BOOLEAN = XSD + 'boolean';

  function state() { return Parser._state; }

  function graphTerm() { return state().graph || Parser.factory.defaultGraph(); }

  // Quads are buffered per statement and flushed by finishStatement so the
  // N-Quads graph label (which appears after the object list) can set the
  // graph before the quads are emitted.
  function emitQuad(s, p, o) { state().pending.push([s, p, o]); }

  function finishStatement() {
    var st = state();
    var g = graphTerm();
    for (var i = 0; i < st.pending.length; i++) {
      var q = st.pending[i];
      Parser.quads.push(Parser.factory.quad(q[0], q[1], q[2], g));
    }
    st.pending = [];
  }

  function freshBnode() {
    return Parser.factory.blankNode('b' + (++state().bnodeCounter));
  }

  // --- RFC 3986 §5.2-5.3 relative-reference resolution ---
  // RDF 1.1 Turtle §6.3 (and RDF 1.2 Concepts) resolve relative IRIs with
  // the RFC 3986 algorithm, not WHATWG URL normalization. The two disagree on
  // edge cases such as a network-path reference with an empty path (`//host`,
  // which RFC 3986 recomposes to `scheme://host` with no trailing slash while
  // WHATWG appends "/"), so resolution is implemented from the RFC directly.

  // Splits a URI reference into its five RFC 3986 components.
  function parseUri3986(uri) {
    var m = /^(?:([^:\/?#]+):)?(?:\/\/([^\/?#]*))?([^?#]*)(?:\?([^#]*))?(?:#([\s\S]*))?$/.exec(uri);
    return {
      scheme: m[1],
      authority: m[2],
      path: m[3] || '',
      query: m[4],
      fragment: m[5],
    };
  }

  // RFC 3986 §5.2.4 remove_dot_segments.
  function removeDotSegments3986(path) {
    var input = path;
    var output = '';
    while (input.length > 0) {
      if (input.indexOf('../') === 0) {
        input = input.slice(3);
      } else if (input.indexOf('./') === 0) {
        input = input.slice(2);
      } else if (input.indexOf('/./') === 0) {
        input = '/' + input.slice(3);
      } else if (input === '/.') {
        input = '/';
      } else if (input.indexOf('/../') === 0) {
        input = '/' + input.slice(4);
        output = output.replace(/\/?[^\/]*$/, '');
      } else if (input === '/..') {
        input = '/';
        output = output.replace(/\/?[^\/]*$/, '');
      } else if (input === '.' || input === '..') {
        input = '';
      } else {
        var seg = /^\/?[^\/]*/.exec(input)[0];
        output += seg;
        input = input.slice(seg.length);
      }
    }
    return output;
  }

  // RFC 3986 §5.2.3 merge (base path with a relative reference path).
  function mergePaths3986(base, refPath) {
    if (base.authority !== undefined && base.path === '') {
      return '/' + refPath;
    }
    return base.path.slice(0, base.path.lastIndexOf('/') + 1) + refPath;
  }

  // RFC 3986 §5.2.2 transform + §5.3 recomposition.
  function resolveRfc3986(base, ref) {
    var B = parseUri3986(base);
    var R = parseUri3986(ref);
    var T = {
      scheme: undefined,
      authority: undefined,
      path: '',
      query: undefined,
      fragment: undefined,
    };

    if (R.scheme !== undefined) {
      T.scheme = R.scheme;
      T.authority = R.authority;
      T.path = removeDotSegments3986(R.path);
      T.query = R.query;
    } else {
      if (R.authority !== undefined) {
        T.authority = R.authority;
        T.path = removeDotSegments3986(R.path);
        T.query = R.query;
      } else {
        if (R.path === '') {
          T.path = B.path;
          T.query = R.query !== undefined ? R.query : B.query;
        } else {
          T.path = R.path.charAt(0) === '/'
            ? removeDotSegments3986(R.path)
            : removeDotSegments3986(mergePaths3986(B, R.path));
          T.query = R.query;
        }
        T.authority = B.authority;
      }
      T.scheme = B.scheme;
    }
    T.fragment = R.fragment;

    var result = '';
    if (T.scheme !== undefined) result += T.scheme + ':';
    if (T.authority !== undefined) result += '//' + T.authority;
    result += T.path;
    if (T.query !== undefined) result += '?' + T.query;
    if (T.fragment !== undefined) result += '#' + T.fragment;
    return result;
  }

  function resolveIri(iri) {
    // An IRI that already has a scheme is already resolved (this also keeps
    // opaque-scheme IRIs such as urn: untouched).
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(iri)) return iri;
    if (!Parser.base) return iri;
    try {
      return resolveRfc3986(Parser.base, iri);
    } catch (e) {
      return Parser.base + iri;
    }
  }

  function decodeUchar(m, u4, u8) {
    var cp = parseInt(u4 || u8, 16);
    if (cp >= 0xD800 && cp <= 0xDFFF) {
      throw new Error('Invalid Unicode escape (surrogate code point): ' + m);
    }
    return String.fromCodePoint(cp);
  }

  function unescapeString(raw) {
    var quotes = /^'''|^\"\"\"|^'|^\"/.exec(raw)[0];
    var body = raw.slice(quotes.length, raw.length - quotes.length);
    return body
      .replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar)
      .replace(/\\([tbnrf"'\\])/g, function (m, ch) {
        return { t: '\t', b: '\b', n: '\n', r: '\r', f: '\f', '"': '"', "'": "'", '\\': '\\' }[ch];
      });
  }

  function unescapeIri(iri) {
    var result = iri.replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar);
    // IRIREF excludes U+0000-U+0020 and <>"{}|^`\\; an escape must not
    // smuggle any of them into the decoded IRI.
    if (/[\u0000-\u0020<>"{}|^`\\]/.test(result)) {
      throw new Error('Invalid IRI escape: disallowed character');
    }
    return result;
  }

  function resolvePrefixed(tok) {
    var i = tok.indexOf(':');
    var prefix = tok.slice(0, i);
    var ns = Parser.prefixes[prefix];
    if (ns == null) {
      throw new Error('Undefined prefix: ' + prefix + ':');
    }
    // PN_LOCAL_ESC sequences (\_ \~ \. \- \! \$ \& \' \( \) \* \+ \, \; \= \/ \? \# \@ \%)
    // denote the literal character (TriG 4.5 PN_LOCAL_ESC); percent-escapes are kept as-is.
    return ns + tok.slice(i + 1).replace(/\\([_~.\-!$&'()*+,;=/?#@%])/g, '$1');
  }

  function addPrefix(pnameNs, iriTok) {
    var prefix = pnameNs.slice(0, -1);
    Parser.prefixes[prefix] = resolveIri(iriTok.slice(1, -1));
  }

  // --- RDF 1.2 literal well-formedness (Turtle 3.3 / N-Triples term
  //     constructors): language tags MUST be well-formed per BCP47
  //     (RFC 5646 section 2.2.9), and rdf:langString / rdf:dirLangString
  //     MUST NOT be written as explicit datatype IRIs. ---

  function isWellFormedBcp47(tag) {
    var ALPHA = /^[A-Za-z]+$/;
    var ALPHANUM = /^[A-Za-z0-9]+$/;
    var DIGIT = /^[0-9]+$/;
    // RFC 5646 section 2.2.8 grandfathered "irregular" tags, which do not
    // match the langtag ABNF but are nonetheless well-formed.
    var IRREGULAR = {
      'en-GB-oed': 1, 'i-ami': 1, 'i-bnn': 1, 'i-default': 1,
      'i-enochian': 1, 'i-hak': 1, 'i-klingon': 1, 'i-lux': 1,
      'i-mingo': 1, 'i-navajo': 1, 'i-pwn': 1, 'i-tao': 1,
      'i-tay': 1, 'i-tsu': 1, 'sgn-BE-FR': 1, 'sgn-BE-NL': 1,
      'sgn-CH-DE': 1,
    };
    if (Object.prototype.hasOwnProperty.call(IRREGULAR, tag)) return true;

    // privateuse = "x" 1*("-" 1*8alphanum)
    if (/^x(-[A-Za-z0-9]{1,8})+$/.test(tag)) return true;

    var subtags = tag.split('-');
    var i = 0;
    // language = 2*3ALPHA ["-" extlang] / 4ALPHA / 5*8ALPHA
    var lang = subtags[i++];
    if (lang.length >= 2 && lang.length <= 3) {
      if (!ALPHA.test(lang)) return false;
      // extlang = 3ALPHA *2("-" 3ALPHA)
      var extlangs = 0;
      while (i < subtags.length && extlangs < 3 &&
          subtags[i].length === 3 && ALPHA.test(subtags[i])) {
        i++;
        extlangs++;
      }
    } else if (lang.length === 4) {
      if (!ALPHA.test(lang)) return false;
    } else if (lang.length >= 5 && lang.length <= 8) {
      if (!ALPHA.test(lang)) return false;
    } else {
      return false;
    }

    // script = 4ALPHA
    if (i < subtags.length && subtags[i].length === 4 &&
        ALPHA.test(subtags[i])) {
      i++;
    }

    // region = 2ALPHA / 3DIGIT
    if (i < subtags.length) {
      var region = subtags[i];
      if ((region.length === 2 && ALPHA.test(region)) ||
          (region.length === 3 && DIGIT.test(region))) {
        i++;
      }
    }

    // variant = 5*8alphanum / (DIGIT 3alphanum)
    while (i < subtags.length) {
      var variant = subtags[i];
      var isVariant = (variant.length >= 5 && variant.length <= 8 &&
        ALPHANUM.test(variant)) ||
        (variant.length === 4 && DIGIT.test(variant.charAt(0)) &&
          ALPHANUM.test(variant));
      if (!isVariant) break;
      i++;
    }

    // extension = singleton 1*("-" 2*8alphanum), where singleton is a single
    // alphanumeric other than x/X.
    while (i < subtags.length && /^[0-9A-WY-Za-wy-z]$/.test(subtags[i])) {
      i++;
      var extCount = 0;
      while (i < subtags.length && subtags[i].length >= 2 &&
          subtags[i].length <= 8 && ALPHANUM.test(subtags[i])) {
        i++;
        extCount++;
      }
      if (extCount === 0) return false;
    }

    // privateuse = "x" 1*("-" 1*8alphanum)
    if (i < subtags.length && subtags[i] === 'x') {
      i++;
      var puCount = 0;
      while (i < subtags.length && subtags[i].length >= 1 &&
          subtags[i].length <= 8 && ALPHANUM.test(subtags[i])) {
        i++;
        puCount++;
      }
      if (puCount === 0) return false;
    }

    return i === subtags.length;
  }

  function langDirTag(langDir) {
    // langDir is the LANG_DIR token after its leading '@' (e.g. "en--ltr").
    // The optional "--ltr"/"--rtl" direction suffix is guaranteed by the
    // LANG_DIR terminal; validate only the language-tag portion and return a
    // directional-language pair so the factory can set the rdf:dirLangString
    // datatype when a direction is present.
    var dash = langDir.indexOf('--');
    var tag = dash === -1 ? langDir : langDir.slice(0, dash);
    if (!isWellFormedBcp47(tag)) {
      throw new Error('Language tag is not well-formed per BCP47: ' + tag);
    }
    return dash === -1
      ? { language: tag }
      : { language: tag, direction: langDir.slice(dash + 2) };
  }

  function datatypeIri(dt) {
    if (dt.value === RDF_LANGSTRING || dt.value === RDF_DIRLANGSTRING) {
      throw new Error(
        'rdf:langString and rdf:dirLangString must not be written as an explicit datatype IRI'
      );
    }
    return dt;
  }

  // --- RDF 1.2 reifier / annotation state machine (TriG 5.3.4-5.3.7) ---


  function startAnnotation() {
    var st = state();
    st.saveStack.push({
      subject: st.subject,
      predicate: st.predicate,
      tripleTerm: st.tripleTerm,
      reifier: st.reifier,
    });
    st.tripleTerm = Parser.factory.quad(st.subject, st.predicate, st.object);
    st.reifier = undefined;
  }

  function endAnnotation() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    st.tripleTerm = saved.tripleTerm;
    st.reifier = saved.reifier;
  }

  function startAnnotationBlock() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    st.subject = st.reifier;
  }

  function endAnnotationBlock() {
    state().reifier = undefined;
  }

  function applyReifier(reifierTerm) {
    var st = state();
    st.reifier = reifierTerm || freshBnode();
    emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
  }

  // Finishing a reified triple (TriG 5.3.5): if no `~ reifier` was matched,
  // assign a fresh blank node; the reifying triple was already emitted by the
  // reifier production when a reifier was present. The node produced by the
  // production is the reifier.
  function nn(value) { return Parser.factory.namedNode(value); }

  function startReifiedTriple() {
    var st = state();
    st.reifierStack.push({ reifier: st.reifier, tripleTerm: st.tripleTerm });
    st.reifier = undefined;
  }

  function finishReifiedTriple() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    var node = st.reifier;
    var saved = st.reifierStack.pop();
    st.reifier = saved.reifier;
    st.tripleTerm = saved.tripleTerm;
    return node;
  }

  // Emits the triple for a parsed object and prepares the annotation context
  // (TriG 5.3.3 / 5.3.6). Returns the object value.
  function emitObject(o) {
    state().object = o;
    emitQuad(state().subject, state().predicate, o);
    startAnnotation();
    return o;
  }

  // --- blank node property lists (TriG 5.3.8) ---

  function startBnpl() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.bnplNode = freshBnode();
    st.subject = st.bnplNode;
  }

  function endBnpl() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    return st.bnplNode;
  }

  // --- collections (TriG 5.3.9) ---

  function startCollection() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.collectionStack.push({ items: [] });
  }

  function collectionAdd(item) {
    state().collectionStack[state().collectionStack.length - 1].items.push(item);
  }

  function endCollection() {
    var st = state();
    var coll = st.collectionStack.pop();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    var items = coll.items;
    if (items.length === 0) {
      return Parser.factory.namedNode(RDF_NIL);
    }
    var head = freshBnode();
    var cur = head;
    for (var i = 0; i < items.length; i++) {
      emitQuad(cur, nn(RDF_FIRST), items[i]);
      if (i < items.length - 1) {
        var next = freshBnode();
        emitQuad(cur, nn(RDF_REST), next);
        cur = next;
      } else {
        emitQuad(cur, nn(RDF_REST), nn(RDF_NIL));
      }
    }
    return head;
  }
%}

%lex

// Terminal regexes — W3C RDF 1.2 TriG section 4.5 (productions for terminals).
HEX           [0-9A-Fa-f]
UCHAR         "\\u"{HEX}{HEX}{HEX}{HEX}|"\\U"{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}{HEX}
ECHAR         "\\"[tbnrf"'\\]
PN_CHARS_BASE [A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]
PN_CHARS_U    ({PN_CHARS_BASE}|"_")
PN_CHARS      ({PN_CHARS_U}|"-"|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])
PN_PREFIX     ({PN_CHARS_BASE})(({PN_CHARS}|".")*{PN_CHARS})?
PN_LOCAL      ({PN_CHARS_U}|":"|[0-9]|{PLX})(({PN_CHARS}|"."|":"|{PLX})*({PN_CHARS}|":"|{PLX}))?
PLX           ({PERCENT}|{PN_LOCAL_ESC})
PERCENT       "%"[0-9A-Fa-f]{2}
PN_LOCAL_ESC  "\\"("_"|"~"|"."|"-"|"!"|"$"|"&"|"'"|"("|")"|"*"|"+"|","|";"|"="|"/"|"?"|"#"|"@"|"%")
PNAME_NS      ({PN_PREFIX}?":")
PNAME_LN      ({PNAME_NS}{PN_LOCAL})
BLANK_NODE_LABEL "_:"({PN_CHARS_U}|[0-9])(({PN_CHARS}|".")*{PN_CHARS})?
IRIREF        "<"(?:[^<>\"{}|^`\\\u0000-\u0020]|{UCHAR})*">"
LANG_DIR      "@"[a-zA-Z]+("-"[a-zA-Z0-9]+)*("--"("ltr"|"rtl"))?
INTEGER       [+-]?[0-9]+
DECIMAL       [+-]?([0-9]*"."[0-9]+)
DOUBLE        [+-]?(([0-9]+"."[0-9]*{EXPONENT})|("."[0-9]+{EXPONENT})|([0-9]+{EXPONENT}))
EXPONENT      [eE][+-]?[0-9]+
STRING_LITERAL_LONG_QUOTE        "\"\"\""((("\""|"\"\"")?([^"\\]|{ECHAR}|{UCHAR}))*)"\"\"\""
STRING_LITERAL_LONG_SINGLE_QUOTE "'''"((("'"|"''")?([^'\\]|{ECHAR}|{UCHAR}))*)"'''"
STRING_LITERAL_QUOTE             "\""([^\u0022\u005C\u000A\u000D]|{ECHAR}|{UCHAR})*"\""
STRING_LITERAL_SINGLE_QUOTE      "'"([^\u0027\u005C\u000A\u000D]|{ECHAR}|{UCHAR})*"'"
ANON          "["\s*"]"
COMMENT       "#"[^\n\r]*

%options flex

%%

\s+|{COMMENT}                  /* ignore */
"@prefix"                      return 'PREFIX_ID'
"@base"                        return 'BASE_ID'
"@version"                     return 'VERSION_ID'
[Pp][Rr][Ee][Ff][Ii][Xx]       return 'SPARQL_PREFIX'
[Bb][Aa][Ss][Ee]               return 'SPARQL_BASE'
[Vv][Ee][Rr][Ss][Ii][Oo][Nn]   return 'SPARQL_VERSION'
"GRAPH"                        return 'GRAPH'
"a"                            return 'a'
"true"|"false"                 return 'BOOLEAN'
"^^"                           return '^^'
"<<("                          return '<<('
")>>"                          return ')>>'
"<<"                           return '<<'
">>"                           return '>>'
"~"                            return '~'
"{|"                           return '{|'
"|}"                           return '|}'
"."                            return '.'
";"                            return ';'
","                            return ','
"("                            return '('
")"                            return ')'
"["                            return '['
"]"                            return ']'
"{"                            return '{'
"}"                            return '}'
{ANON}                         return 'ANON'
{IRIREF}                       return 'IRIREF'
{PNAME_LN}                     return 'PNAME_LN'
{PNAME_NS}                     return 'PNAME_NS'
{BLANK_NODE_LABEL}             return 'BLANK_NODE_LABEL'
{LANG_DIR}                     return 'LANG_DIR'
{STRING_LITERAL_LONG_QUOTE}    return 'STRING_LONG'
{STRING_LITERAL_LONG_SINGLE_QUOTE} return 'STRING_LONG'
{STRING_LITERAL_QUOTE}         return 'STRING'
{STRING_LITERAL_SINGLE_QUOTE}  return 'STRING'
{DOUBLE}                       return 'DOUBLE'
{DECIMAL}                      return 'DECIMAL'
{INTEGER}                      return 'INTEGER'
.                              return 'INVALID'
/lex

%%

document
  : (directive | block)*
  ;

directive
  : PREFIX_ID PNAME_NS IRIREF "." -> addPrefix($2, $3)
  | SPARQL_PREFIX PNAME_NS IRIREF -> addPrefix($2, $3)
  | BASE_ID IRIREF "."            -> (Parser.base = resolveIri($2.slice(1, -1)))
  | SPARQL_BASE IRIREF            -> (Parser.base = resolveIri($2.slice(1, -1)))
  | VERSION_ID STRING "."         
  | SPARQL_VERSION STRING         
  ;

block
  : triplesOrGraph
  | wrappedGraph
  | triples2
  | GRAPH graphLabelHeader wrappedGraph -> (state().graph = undefined)
  ;

// labelOrSubject in subject position: record it as the statement subject and
// reset the graph to the default (TriG 5.3.1).
subjectHeader
  : labelOrSubject -> (state().subject = $1, state().graph = undefined)
  ;

// labelOrSubject in graph-label position: record it as the current graph.
graphLabelHeader
  : labelOrSubject -> (state().graph = $1)
  ;

// N-Quads-style graph label on a top-level statement (after the object list).
setGraphLabel
  : iri -> (state().graph = $1)
  | BLANK_NODE_LABEL -> (state().graph = Parser.factory.blankNode($1.slice(2)))
  ;

// A reified triple used as a statement subject: its node (the reifier) becomes
// the subject for the following predicate-object list (TriG 5.3.5).
reifiedSubject
  : reifiedTriple -> (state().subject = $1)
  ;

// A blank node property list used as a statement subject: its node becomes the
// subject for the following predicate-object list (TriG 5.3.8). The bare
// blankNodePropertyList production restores the enclosing subject/predicate, so
// we capture the node here before any outer predicate-object list runs.
bnplSubject
  : blankNodePropertyList -> (state().subject = $1)
  ;

triplesOrGraph
  : graphLabelHeader wrappedGraph -> (state().graph = undefined)
  | subjectHeader predicateObjectList "." -> finishStatement()
  | subjectHeader predicateObjectList setGraphLabel "." -> (finishStatement(), state().graph = undefined)
  | reifiedSubject predicateObjectList? "." -> finishStatement()
  ;

triples2
  : bnplSubject predicateObjectList? "." -> finishStatement()
  | collectionSubject predicateObjectList "." -> finishStatement()
  ;

collectionSubject
  : collection -> (state().subject = $1)
  ;

wrappedGraph
  : "{" triplesBlock? "}"
  ;

// A triple statement inside a graph block: flush its buffered quads into the
// current graph when the statement completes (before '.' or '}').
triplesStatement
  : triples -> finishStatement()
  ;

triplesBlock
  : triplesStatement ("." triplesBlock?)?
  ;

labelOrSubject
  : iri -> $1
  | BlankNode -> $1
  ;

triples
  : subject predicateObjectList
  | bnplSubject predicateObjectList?
  | reifiedSubject predicateObjectList?
  ;

subject
  : iri -> (state().subject = $1)
  | BlankNode -> (state().subject = $1)
  | collection -> (state().subject = $1)
  ;

predicateObjectList
  : verb objectList
  | predicateObjectList ";" verb objectList
  | predicateObjectList ";"
  ;

objectList
  : objectEmission annotation -> endAnnotation()
  | objectList "," objectEmission annotation -> endAnnotation()
  ;

// The object production with its triple emission and the annotation start
// (TriG 5.3.3 and 5.3.6): the object value is recorded, the triple
// curSubject curPredicate object is emitted, and the annotation context
// (tripleTerm, saved subject/predicate, cleared reifier) is prepared.
objectEmission
  : object -> emitObject($1)
  ;

verb
  : predicate -> (state().predicate = $1)
  | "a" -> (state().predicate = Parser.factory.namedNode(RDF_TYPE))
  ;

// A verb inside a triple term or reified-triple body must not clobber the
// enclosing statement's predicate (TriG 5.3.4): return the predicate term
// without the state().predicate side effect that the statement-level `verb`
// production performs.
ttVerb
  : predicate -> $1
  | "a" -> Parser.factory.namedNode(RDF_TYPE)
  ;

predicate
  : iri -> $1
  ;

object
  : iri -> $1
  | BlankNode -> $1
  | collection -> $1
  | blankNodePropertyList -> $1
  | literal -> $1
  | tripleTerm -> $1
  | reifiedTriple -> $1
  ;

literal
  : RDFLiteral -> $1
  | NumericLiteral -> $1
  | BooleanLiteral -> $1
  ;

RDFLiteral
  : STRING -> Parser.factory.literal(unescapeString($1))
  | STRING_LONG -> Parser.factory.literal(unescapeString($1))
  | STRING LANG_DIR -> Parser.factory.literal(unescapeString($1), langDirTag($2.slice(1)))
  | STRING_LONG LANG_DIR -> Parser.factory.literal(unescapeString($1), langDirTag($2.slice(1)))
  | STRING "^^" iri -> Parser.factory.literal(unescapeString($1), datatypeIri($3))
  | STRING_LONG "^^" iri -> Parser.factory.literal(unescapeString($1), datatypeIri($3))
  ;

NumericLiteral
  : INTEGER -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_INTEGER))
  | DECIMAL -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_DECIMAL))
  | DOUBLE -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_DOUBLE))
  ;

BooleanLiteral
  : BOOLEAN -> Parser.factory.literal($1, Parser.factory.namedNode(XSD_BOOLEAN))
  ;

bnplStart
  : "[" -> startBnpl()
  ;

blankNodePropertyList
  : bnplStart predicateObjectList "]" -> endBnpl()
  ;

collectionStart
  : "(" -> startCollection()
  ;

collection
  : collectionStart ")" -> endCollection()
  | collectionStart collectionItems ")" -> endCollection()
  ;

collectionItems
  : object -> collectionAdd($1)
  | collectionItems object -> collectionAdd($2)
  ;

iri
  : IRIREF -> Parser.factory.namedNode(resolveIri(unescapeIri($1.slice(1, -1))))
  | PNAME_LN -> Parser.factory.namedNode(resolvePrefixed($1))
  | PNAME_NS -> Parser.factory.namedNode(resolvePrefixed($1))
  ;

PrefixedName
  : PNAME_LN -> $1
  | PNAME_NS -> $1
  ;

BlankNode
  : BLANK_NODE_LABEL -> Parser.factory.blankNode($1.slice(2))
  | ANON -> freshBnode()
  ;

tripleTerm
  : "<<(" ttSubject ttVerb ttObject ")>>" -> Parser.factory.quad($2, $3, $4)
  ;

ttSubject
  : iri -> $1
  | BlankNode -> $1
  ;

ttObject
  : iri -> $1
  | BlankNode -> $1
  | literal -> $1
  | tripleTerm -> $1
  ;

// The subject-verb-object body of a reified triple; records the triple term
// before the optional reifier so `~ r` can emit the reifying triple
// (TriG 5.3.4).
reifiedTripleBody
  : rtSubject ttVerb rtObject -> (state().tripleTerm = Parser.factory.quad($1, $2, $3))
  ;

reifiedTripleStart
  : "<<" -> startReifiedTriple()
  ;

reifiedTriple
  : reifiedTripleStart reifiedTripleBody reifier? ">>" -> finishReifiedTriple()
  ;

rtSubject
  : iri -> $1
  | BlankNode -> $1
  | reifiedTriple -> $1
  ;

rtObject
  : iri -> $1
  | BlankNode -> $1
  | literal -> $1
  | tripleTerm -> $1
  | reifiedTriple -> $1
  ;

reifier
  : "~" -> applyReifier(undefined)
  | "~" iri -> applyReifier($2)
  | "~" BlankNode -> applyReifier($2)
  ;

annotation
  : annotationPart*
  ;

annotationPart
  : reifier
  | annotationBlock
  ;

annotationBlockStart
  : "{|" -> startAnnotationBlock()
  ;

annotationBlock
  : annotationBlockStart predicateObjectList "|}" -> endAnnotationBlock()
  ;
