// @ts-nocheck
// deno-lint-ignore-file
// Generated by `deno task parser:generate` — edit the .jison grammar instead.
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var TurtleParser = (function () {
  var o = function (k, v, o, l) {
      for (o = o || {}, l = k.length; l--; o[k[l]] = v);
      return o;
    },
    $V0 = [1, 6, 7, 8, 10, 11, 12, 13, 15, 20, 26, 36, 69, 72, 75, 77, 85],
    $V1 = [1, 33],
    $V2 = [1, 31],
    $V3 = [1, 34],
    $V4 = [1, 19],
    $V5 = [1, 36],
    $V6 = [1, 37],
    $V7 = [1, 32],
    $V8 = [1, 35],
    $V9 = [1, 28],
    $Va = [1, 50],
    $Vb = [7, 8, 55, 75],
    $Vc = [2, 13],
    $Vd = [7, 8, 9, 38, 55, 75],
    $Ve = [7, 8, 36, 55, 75],
    $Vf = [1, 87],
    $Vg = [1, 88],
    $Vh = [1, 89],
    $Vi = [1, 90],
    $Vj = [1, 91],
    $Vk = [1, 92],
    $Vl = [1, 86],
    $Vm = [
      7,
      8,
      9,
      14,
      26,
      36,
      38,
      49,
      52,
      55,
      61,
      64,
      65,
      66,
      67,
      69,
      70,
      72,
      73,
      75,
      77,
      78,
      81,
      85,
      87,
      89,
      94,
      95,
    ],
    $Vn = [7, 8, 14, 26, 61, 64, 65, 66, 67, 69, 72, 73, 75, 77, 78, 85],
    $Vo = [1, 100],
    $Vp = [7, 8, 14, 26, 61, 64, 65, 66, 67, 69, 72, 75, 77, 78, 85],
    $Vq = [9, 38],
    $Vr = [1, 119],
    $Vs = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      55,
      61,
      64,
      65,
      66,
      67,
      69,
      70,
      72,
      73,
      75,
      77,
      78,
      85,
      89,
      94,
      95,
    ],
    $Vt = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      61,
      64,
      65,
      66,
      67,
      69,
      70,
      72,
      73,
      75,
      77,
      78,
      85,
      89,
      94,
      95,
    ],
    $Vu = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      61,
      64,
      65,
      66,
      67,
      69,
      70,
      72,
      73,
      75,
      77,
      78,
      81,
      85,
      87,
      89,
      94,
      95,
    ],
    $Vv = [7, 8, 9, 26, 38, 49, 70, 75, 95],
    $Vw = [1, 134],
    $Vx = [7, 8, 9, 26, 38, 49, 52, 70, 75, 89, 94, 95],
    $Vy = [2, 124],
    $Vz = [7, 8, 9, 26, 38, 49, 52, 70, 75, 95],
    $VA = [7, 8, 9, 26, 38, 49, 52, 70, 75, 87, 89, 94, 95],
    $VB = [87, 89];
  var parser = {
    trace: function trace() {},
    yy: {},
    symbols_: {
      "error": 2,
      "document": 3,
      "document_repetition0": 4,
      "directive": 5,
      "PREFIX_ID": 6,
      "PNAME_NS": 7,
      "IRIREF": 8,
      ".": 9,
      "SPARQL_PREFIX": 10,
      "BASE_ID": 11,
      "SPARQL_BASE": 12,
      "VERSION_ID": 13,
      "STRING": 14,
      "SPARQL_VERSION": 15,
      "block": 16,
      "triplesOrGraph": 17,
      "wrappedGraph": 18,
      "triples2": 19,
      "GRAPH": 20,
      "graphLabelHeader": 21,
      "subjectHeader": 22,
      "labelOrSubject": 23,
      "setGraphLabel": 24,
      "iri": 25,
      "BLANK_NODE_LABEL": 26,
      "reifiedSubject": 27,
      "reifiedTriple": 28,
      "bnplSubject": 29,
      "blankNodePropertyList": 30,
      "predicateObjectList": 31,
      "triplesOrGraph_option0": 32,
      "triples2_option0": 33,
      "collectionSubject": 34,
      "collection": 35,
      "{": 36,
      "wrappedGraph_option0": 37,
      "}": 38,
      "triplesStatement": 39,
      "triples": 40,
      "triplesBlock": 41,
      "triplesBlock_option0": 42,
      "BlankNode": 43,
      "subject": 44,
      "triples_option0": 45,
      "triples_option1": 46,
      "verb": 47,
      "objectList": 48,
      ";": 49,
      "objectEmission": 50,
      "annotation": 51,
      ",": 52,
      "object": 53,
      "predicate": 54,
      "a": 55,
      "literal": 56,
      "tripleTerm": 57,
      "RDFLiteral": 58,
      "NumericLiteral": 59,
      "BooleanLiteral": 60,
      "STRING_LONG": 61,
      "LANG_DIR": 62,
      "^^": 63,
      "INTEGER": 64,
      "DECIMAL": 65,
      "DOUBLE": 66,
      "BOOLEAN": 67,
      "bnplStart": 68,
      "[": 69,
      "]": 70,
      "collectionStart": 71,
      "(": 72,
      ")": 73,
      "collectionItems": 74,
      "PNAME_LN": 75,
      "PrefixedName": 76,
      "ANON": 77,
      "<<(": 78,
      "ttSubject": 79,
      "ttObject": 80,
      ")>>": 81,
      "reifiedTripleBody": 82,
      "rtSubject": 83,
      "rtObject": 84,
      "<<": 85,
      "reifiedTriple_option0": 86,
      ">>": 87,
      "reifier": 88,
      "~": 89,
      "annotation_repetition0": 90,
      "annotationPart": 91,
      "annotationBlock": 92,
      "annotationBlockStart": 93,
      "{|": 94,
      "|}": 95,
      "document_repetition0_group0": 96,
      "triplesBlock_option0_option0": 97,
      "$accept": 0,
      "$end": 1,
    },
    terminals_: {
      2: "error",
      6: "PREFIX_ID",
      7: "PNAME_NS",
      8: "IRIREF",
      9: ".",
      10: "SPARQL_PREFIX",
      11: "BASE_ID",
      12: "SPARQL_BASE",
      13: "VERSION_ID",
      14: "STRING",
      15: "SPARQL_VERSION",
      20: "GRAPH",
      26: "BLANK_NODE_LABEL",
      36: "{",
      38: "}",
      49: ";",
      52: ",",
      55: "a",
      61: "STRING_LONG",
      62: "LANG_DIR",
      63: "^^",
      64: "INTEGER",
      65: "DECIMAL",
      66: "DOUBLE",
      67: "BOOLEAN",
      69: "[",
      70: "]",
      72: "(",
      73: ")",
      75: "PNAME_LN",
      77: "ANON",
      78: "<<(",
      81: ")>>",
      85: "<<",
      87: ">>",
      89: "~",
      94: "{|",
      95: "|}",
    },
    productions_: [
      0,
      [3, 1],
      [5, 4],
      [5, 3],
      [5, 3],
      [5, 2],
      [5, 3],
      [5, 2],
      [16, 1],
      [16, 1],
      [16, 1],
      [16, 3],
      [22, 1],
      [21, 1],
      [24, 1],
      [24, 1],
      [27, 1],
      [29, 1],
      [17, 2],
      [17, 3],
      [17, 4],
      [17, 3],
      [19, 3],
      [19, 3],
      [34, 1],
      [18, 3],
      [39, 1],
      [41, 2],
      [23, 1],
      [23, 1],
      [40, 2],
      [40, 2],
      [40, 2],
      [44, 1],
      [44, 1],
      [44, 1],
      [31, 2],
      [31, 4],
      [31, 2],
      [48, 2],
      [48, 4],
      [50, 1],
      [47, 1],
      [47, 1],
      [54, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [56, 1],
      [56, 1],
      [56, 1],
      [58, 1],
      [58, 1],
      [58, 2],
      [58, 2],
      [58, 3],
      [58, 3],
      [59, 1],
      [59, 1],
      [59, 1],
      [60, 1],
      [68, 1],
      [30, 3],
      [71, 1],
      [35, 2],
      [35, 3],
      [74, 1],
      [74, 2],
      [25, 1],
      [25, 1],
      [25, 1],
      [76, 1],
      [76, 1],
      [43, 1],
      [43, 1],
      [57, 5],
      [79, 1],
      [79, 1],
      [80, 1],
      [80, 1],
      [80, 1],
      [80, 1],
      [82, 3],
      [28, 4],
      [83, 1],
      [83, 1],
      [83, 1],
      [84, 1],
      [84, 1],
      [84, 1],
      [84, 1],
      [84, 1],
      [88, 1],
      [88, 2],
      [88, 2],
      [51, 1],
      [91, 1],
      [91, 1],
      [93, 1],
      [92, 3],
      [96, 1],
      [96, 1],
      [4, 0],
      [4, 2],
      [32, 0],
      [32, 1],
      [33, 0],
      [33, 1],
      [37, 0],
      [37, 1],
      [97, 0],
      [97, 1],
      [42, 0],
      [42, 2],
      [45, 0],
      [45, 1],
      [46, 0],
      [46, 1],
      [86, 0],
      [86, 1],
      [90, 0],
      [90, 2],
    ],
    performAction: function anonymous(
      yytext,
      yyleng,
      yylineno,
      yy,
      yystate, /* action[1] */
      $$, /* vstack */
      _$, /* lstack */
    ) {
      /* this == yyval */

      var $0 = $$.length - 1;
      switch (yystate) {
        case 2:
          this.$ = addPrefix($$[$0 - 2], $$[$0 - 1]);
          break;
        case 3:
          this.$ = addPrefix($$[$0 - 1], $$[$0]);
          break;
        case 4:
          this.$ = Parser.base = resolveIri($$[$0 - 1].slice(1, -1));
          break;
        case 5:
          this.$ = Parser.base = resolveIri($$[$0].slice(1, -1));
          break;
        case 11:
        case 18:
          this.$ = state().graph = undefined;
          break;
        case 12:
          this.$ = (state().subject = $$[$0], state().graph = undefined);
          break;
        case 13:
        case 14:
          this.$ = state().graph = $$[$0];
          break;
        case 15:
          this.$ = state().graph = Parser.factory.blankNode($$[$0].slice(2));
          break;
        case 16:
        case 17:
        case 24:
        case 33:
        case 34:
        case 35:
          this.$ = state().subject = $$[$0];
          break;
        case 19:
        case 21:
        case 22:
        case 23:
        case 26:
          this.$ = finishStatement();
          break;
        case 20:
          this.$ = (finishStatement(), state().graph = undefined);
          break;
        case 28:
        case 29:
        case 44:
        case 45:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
        case 75:
        case 76:
        case 80:
        case 81:
        case 82:
        case 83:
        case 84:
        case 85:
        case 88:
        case 89:
        case 90:
        case 91:
        case 92:
        case 93:
        case 94:
        case 95:
          this.$ = $$[$0];
          break;
        case 39:
        case 40:
          this.$ = endAnnotation();
          break;
        case 41:
          this.$ = emitObject($$[$0]);
          break;
        case 42:
          this.$ = state().predicate = $$[$0];
          break;
        case 43:
          this.$ = state().predicate = Parser.factory.namedNode(RDF_TYPE);
          break;
        case 55:
        case 56:
          this.$ = Parser.factory.literal(unescapeString($$[$0]));
          break;
        case 57:
        case 58:
          this.$ = Parser.factory.literal(
            unescapeString($$[$0 - 1]),
            $$[$0].slice(1),
          );
          break;
        case 59:
        case 60:
          this.$ = Parser.factory.literal(unescapeString($$[$0 - 2]), $$[$0]);
          break;
        case 61:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_INTEGER),
          );
          break;
        case 62:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_DECIMAL),
          );
          break;
        case 63:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_DOUBLE),
          );
          break;
        case 64:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_BOOLEAN),
          );
          break;
        case 65:
          this.$ = startBnpl();
          break;
        case 66:
          this.$ = endBnpl();
          break;
        case 67:
          this.$ = startCollection();
          break;
        case 68:
        case 69:
          this.$ = endCollection();
          break;
        case 70:
        case 71:
          this.$ = collectionAdd($$[$0]);
          break;
        case 72:
          this.$ = Parser.factory.namedNode(
            resolveIri(unescapeIri($$[$0].slice(1, -1))),
          );
          break;
        case 73:
        case 74:
          this.$ = Parser.factory.namedNode(resolvePrefixed($$[$0]));
          break;
        case 77:
          this.$ = Parser.factory.blankNode($$[$0].slice(2));
          break;
        case 78:
          this.$ = freshBnode();
          break;
        case 79:
          this.$ = Parser.factory.quad($$[$0 - 3], $$[$0 - 2], $$[$0 - 1]);
          break;
        case 86:
          this.$ = state().tripleTerm = Parser.factory.quad(
            $$[$0 - 2],
            $$[$0 - 1],
            $$[$0],
          );
          break;
        case 87:
          this.$ = finishReifiedTriple();
          break;
        case 96:
          this.$ = applyReifier(undefined);
          break;
        case 97:
        case 98:
          this.$ = applyReifier($$[$0]);
          break;
        case 102:
          this.$ = startAnnotationBlock();
          break;
        case 103:
          this.$ = endAnnotationBlock();
          break;
        case 106:
        case 124:
          this.$ = [];
          break;
        case 107:
        case 125:
          $$[$0 - 1].push($$[$0]);
          break;
      }
    },
    table: [
      o($V0, [2, 106], { 3: 1, 4: 2 }),
      { 1: [3] },
      {
        1: [2, 1],
        5: 4,
        6: [1, 6],
        7: $V1,
        8: $V2,
        10: [1, 7],
        11: [1, 8],
        12: [1, 9],
        13: [1, 10],
        15: [1, 11],
        16: 5,
        17: 12,
        18: 13,
        19: 14,
        20: [1, 15],
        21: 16,
        22: 17,
        23: 22,
        25: 26,
        26: $V3,
        27: 18,
        28: 23,
        29: 20,
        30: 24,
        34: 21,
        35: 25,
        36: $V4,
        43: 27,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        85: $V9,
        96: 3,
      },
      o($V0, [2, 107]),
      o($V0, [2, 104]),
      o($V0, [2, 105]),
      { 7: [1, 38] },
      { 7: [1, 39] },
      { 8: [1, 40] },
      { 8: [1, 41] },
      { 14: [1, 42] },
      { 14: [1, 43] },
      o($V0, [2, 8]),
      o($V0, [2, 9]),
      o($V0, [2, 10]),
      {
        7: $V1,
        8: $V2,
        21: 44,
        23: 45,
        25: 26,
        26: $V3,
        43: 27,
        75: $V7,
        77: $V8,
      },
      { 18: 46, 36: $V4 },
      { 7: $V1, 8: $V2, 25: 51, 31: 47, 47: 48, 54: 49, 55: $Va, 75: $V7 },
      {
        7: $V1,
        8: $V2,
        9: [2, 108],
        25: 51,
        31: 53,
        32: 52,
        47: 48,
        54: 49,
        55: $Va,
        75: $V7,
      },
      {
        7: $V1,
        8: $V2,
        25: 61,
        26: $V3,
        27: 60,
        28: 23,
        29: 59,
        30: 24,
        35: 63,
        37: 54,
        38: [2, 112],
        39: 56,
        40: 57,
        41: 55,
        43: 62,
        44: 58,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        85: $V9,
      },
      {
        7: $V1,
        8: $V2,
        9: [2, 110],
        25: 51,
        31: 65,
        33: 64,
        47: 48,
        54: 49,
        55: $Va,
        75: $V7,
      },
      { 7: $V1, 8: $V2, 25: 51, 31: 66, 47: 48, 54: 49, 55: $Va, 75: $V7 },
      o($Vb, [2, 12], { 36: $Vc }),
      o($Vd, [2, 16]),
      o($Vd, [2, 17]),
      o($Vb, [2, 24]),
      o($Ve, [2, 28]),
      o($Ve, [2, 29]),
      {
        7: $V1,
        8: $V2,
        25: 69,
        26: $V3,
        28: 71,
        43: 70,
        75: $V7,
        77: $V8,
        82: 67,
        83: 68,
        85: $V9,
      },
      { 7: $V1, 8: $V2, 25: 51, 31: 72, 47: 48, 54: 49, 55: $Va, 75: $V7 },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 76,
        26: $V3,
        28: 82,
        30: 79,
        35: 78,
        43: 77,
        53: 75,
        56: 80,
        57: 81,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        73: [1, 73],
        74: 74,
        75: $V7,
        77: $V8,
        78: $Vl,
        85: $V9,
      },
      o($Vm, [2, 72]),
      o($Vm, [2, 73]),
      o($Vm, [2, 74]),
      o($Vm, [2, 77]),
      o($Vm, [2, 78]),
      o($Vb, [2, 65]),
      o($Vn, [2, 67]),
      { 8: [1, 93] },
      { 8: [1, 94] },
      { 9: [1, 95] },
      o($V0, [2, 5]),
      { 9: [1, 96] },
      o($V0, [2, 7]),
      { 18: 97, 36: $V4 },
      { 36: $Vc },
      o($V0, [2, 18]),
      {
        7: $V1,
        8: $V2,
        9: [1, 98],
        24: 99,
        25: 101,
        26: [1, 102],
        49: $Vo,
        75: $V7,
      },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 76,
        26: $V3,
        28: 82,
        30: 79,
        35: 78,
        43: 77,
        48: 103,
        50: 104,
        53: 105,
        56: 80,
        57: 81,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        78: $Vl,
        85: $V9,
      },
      o($Vp, [2, 42]),
      o($Vp, [2, 43]),
      o($Vp, [2, 44]),
      { 9: [1, 106] },
      { 9: [2, 109], 49: $Vo },
      { 38: [1, 107] },
      { 38: [2, 113] },
      { 9: [1, 109], 38: [2, 116], 42: 108 },
      o($Vq, [2, 26]),
      { 7: $V1, 8: $V2, 25: 51, 31: 110, 47: 48, 54: 49, 55: $Va, 75: $V7 },
      o($Vq, [2, 118], {
        47: 48,
        54: 49,
        25: 51,
        45: 111,
        31: 112,
        7: $V1,
        8: $V2,
        55: $Va,
        75: $V7,
      }),
      o($Vq, [2, 120], {
        47: 48,
        54: 49,
        25: 51,
        46: 113,
        31: 114,
        7: $V1,
        8: $V2,
        55: $Va,
        75: $V7,
      }),
      o($Vb, [2, 33]),
      o($Vb, [2, 34]),
      o($Vb, [2, 35]),
      { 9: [1, 115] },
      { 9: [2, 111], 49: $Vo },
      { 9: [1, 116], 49: $Vo },
      { 86: 117, 87: [2, 122], 88: 118, 89: $Vr },
      { 7: $V1, 8: $V2, 25: 51, 47: 120, 54: 49, 55: $Va, 75: $V7 },
      o($Vb, [2, 88]),
      o($Vb, [2, 89]),
      o($Vb, [2, 90]),
      { 49: $Vo, 70: [1, 121] },
      o($Vs, [2, 68]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 76,
        26: $V3,
        28: 82,
        30: 79,
        35: 78,
        43: 77,
        53: 123,
        56: 80,
        57: 81,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        73: [1, 122],
        75: $V7,
        77: $V8,
        78: $Vl,
        85: $V9,
      },
      o($Vn, [2, 70]),
      o($Vt, [2, 45]),
      o($Vt, [2, 46]),
      o($Vt, [2, 47]),
      o($Vt, [2, 48]),
      o($Vt, [2, 49]),
      o($Vt, [2, 50]),
      o($Vt, [2, 51]),
      o($Vu, [2, 52]),
      o($Vu, [2, 53]),
      o($Vu, [2, 54]),
      { 7: $V1, 8: $V2, 25: 125, 26: $V3, 43: 126, 75: $V7, 77: $V8, 79: 124 },
      o($Vu, [2, 55], { 62: [1, 127], 63: [1, 128] }),
      o($Vu, [2, 56], { 62: [1, 129], 63: [1, 130] }),
      o($Vu, [2, 61]),
      o($Vu, [2, 62]),
      o($Vu, [2, 63]),
      o($Vu, [2, 64]),
      { 9: [1, 131] },
      o($V0, [2, 3]),
      o($V0, [2, 4]),
      o($V0, [2, 6]),
      o($V0, [2, 11]),
      o($V0, [2, 19]),
      { 9: [1, 132] },
      o([9, 26, 38, 49, 70, 95], [2, 38], {
        54: 49,
        25: 51,
        47: 133,
        7: $V1,
        8: $V2,
        55: $Va,
        75: $V7,
      }),
      { 9: [2, 14] },
      { 9: [2, 15] },
      o($Vv, [2, 36], { 52: $Vw }),
      o($Vx, $Vy, { 51: 135, 90: 136 }),
      o($Vx, [2, 41]),
      o($V0, [2, 21]),
      o($V0, [2, 25]),
      { 38: [2, 27] },
      {
        7: $V1,
        8: $V2,
        25: 61,
        26: $V3,
        27: 60,
        28: 23,
        29: 59,
        30: 24,
        35: 63,
        38: [2, 114],
        39: 56,
        40: 57,
        41: 138,
        43: 62,
        44: 58,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        85: $V9,
        97: 137,
      },
      o($Vq, [2, 30], { 49: $Vo }),
      o($Vq, [2, 31]),
      o($Vq, [2, 119], { 49: $Vo }),
      o($Vq, [2, 32]),
      o($Vq, [2, 121], { 49: $Vo }),
      o($V0, [2, 22]),
      o($V0, [2, 23]),
      { 87: [1, 139] },
      { 87: [2, 123] },
      o([9, 38, 49, 52, 70, 87, 89, 94, 95], [2, 96], {
        25: 140,
        43: 141,
        7: $V1,
        8: $V2,
        26: $V3,
        75: $V7,
        77: $V8,
      }),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 143,
        26: $V3,
        28: 147,
        43: 144,
        56: 145,
        57: 146,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        75: $V7,
        77: $V8,
        78: $Vl,
        84: 142,
        85: $V9,
      },
      o($Vs, [2, 66]),
      o($Vs, [2, 69]),
      o($Vn, [2, 71]),
      { 7: $V1, 8: $V2, 25: 51, 47: 148, 54: 49, 55: $Va, 75: $V7 },
      o($Vb, [2, 80]),
      o($Vb, [2, 81]),
      o($Vu, [2, 57]),
      { 7: $V1, 8: $V2, 25: 149, 75: $V7 },
      o($Vu, [2, 58]),
      { 7: $V1, 8: $V2, 25: 150, 75: $V7 },
      o($V0, [2, 2]),
      o($V0, [2, 20]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 76,
        26: $V3,
        28: 82,
        30: 79,
        35: 78,
        43: 77,
        48: 151,
        50: 104,
        53: 105,
        56: 80,
        57: 81,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        78: $Vl,
        85: $V9,
      },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 76,
        26: $V3,
        28: 82,
        30: 79,
        35: 78,
        43: 77,
        50: 152,
        53: 105,
        56: 80,
        57: 81,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        68: 29,
        69: $V5,
        71: 30,
        72: $V6,
        75: $V7,
        77: $V8,
        78: $Vl,
        85: $V9,
      },
      o($Vz, [2, 39]),
      o($Vz, [2, 99], {
        91: 153,
        88: 154,
        92: 155,
        93: 156,
        89: $Vr,
        94: [1, 157],
      }),
      { 38: [2, 117] },
      { 38: [2, 115] },
      o([
        7,
        8,
        9,
        14,
        26,
        38,
        49,
        52,
        55,
        61,
        64,
        65,
        66,
        67,
        69,
        70,
        72,
        73,
        75,
        77,
        78,
        85,
        87,
        89,
        94,
        95,
      ], [2, 87]),
      o($VA, [2, 97]),
      o($VA, [2, 98]),
      o($VB, [2, 86]),
      o($VB, [2, 91]),
      o($VB, [2, 92]),
      o($VB, [2, 93]),
      o($VB, [2, 94]),
      o($VB, [2, 95]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 159,
        26: $V3,
        43: 160,
        56: 161,
        57: 162,
        58: 83,
        59: 84,
        60: 85,
        61: $Vg,
        64: $Vh,
        65: $Vi,
        66: $Vj,
        67: $Vk,
        75: $V7,
        77: $V8,
        78: $Vl,
        80: 158,
      },
      o($Vu, [2, 59]),
      o($Vu, [2, 60]),
      o($Vv, [2, 37], { 52: $Vw }),
      o($Vx, $Vy, { 90: 136, 51: 163 }),
      o($Vx, [2, 125]),
      o($Vx, [2, 100]),
      o($Vx, [2, 101]),
      { 7: $V1, 8: $V2, 25: 51, 31: 164, 47: 48, 54: 49, 55: $Va, 75: $V7 },
      o($Vb, [2, 102]),
      { 81: [1, 165] },
      { 81: [2, 82] },
      { 81: [2, 83] },
      { 81: [2, 84] },
      { 81: [2, 85] },
      o($Vz, [2, 40]),
      { 49: $Vo, 95: [1, 166] },
      o($Vu, [2, 79]),
      o($Vx, [2, 103]),
    ],
    defaultActions: {
      45: [2, 13],
      55: [2, 113],
      101: [2, 14],
      102: [2, 15],
      108: [2, 27],
      118: [2, 123],
      137: [2, 117],
      138: [2, 115],
      159: [2, 82],
      160: [2, 83],
      161: [2, 84],
      162: [2, 85],
    },
    parseError: function parseError(str, hash) {
      if (hash.recoverable) {
        this.trace(str);
      } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
      }
    },
    parse: function parse(input) {
      var self = this,
        stack = [0],
        tstack = [],
        vstack = [null],
        lstack = [],
        table = this.table,
        yytext = "",
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;
      var args = lstack.slice.call(arguments, 1);
      var lexer = Object.create(this.lexer);
      var sharedState = { yy: {} };
      for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
          sharedState.yy[k] = this.yy[k];
        }
      }
      lexer.setInput(input, sharedState.yy);
      sharedState.yy.lexer = lexer;
      sharedState.yy.parser = this;
      if (typeof lexer.yylloc == "undefined") {
        lexer.yylloc = {};
      }
      var yyloc = lexer.yylloc;
      lstack.push(yyloc);
      var ranges = lexer.options && lexer.options.ranges;
      if (typeof sharedState.yy.parseError === "function") {
        this.parseError = sharedState.yy.parseError;
      } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
      }
      function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
      }
      _token_stack:
      var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        if (typeof token !== "number") {
          token = self.symbols_[token] || token;
        }
        return token;
      };
      var symbol,
        preErrorSymbol,
        state,
        action,
        a,
        r,
        yyval = {},
        p,
        len,
        newState,
        expected;
      while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
          action = this.defaultActions[state];
        } else {
          if (symbol === null || typeof symbol == "undefined") {
            symbol = lex();
          }
          action = table[state] && table[state][symbol];
        }
        if (typeof action === "undefined" || !action.length || !action[0]) {
          var errStr = "";
          expected = [];
          for (p in table[state]) {
            if (this.terminals_[p] && p > TERROR) {
              expected.push("'" + this.terminals_[p] + "'");
            }
          }
          if (lexer.showPosition) {
            errStr = "Parse error on line " + (yylineno + 1) + ":\n" +
              lexer.showPosition() + "\nExpecting " + expected.join(", ") +
              ", got '" + (this.terminals_[symbol] || symbol) + "'";
          } else {
            errStr = "Parse error on line " + (yylineno + 1) + ": Unexpected " +
              (symbol == EOF
                ? "end of input"
                : "'" + (this.terminals_[symbol] || symbol) + "'");
          }
          this.parseError(errStr, {
            text: lexer.match,
            token: this.terminals_[symbol] || symbol,
            line: lexer.yylineno,
            loc: yyloc,
            expected: expected,
          });
        }
        if (action[0] instanceof Array && action.length > 1) {
          throw new Error(
            "Parse Error: multiple actions possible at state: " + state +
              ", token: " + symbol,
          );
        }
        switch (action[0]) {
          case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
              yyleng = lexer.yyleng;
              yytext = lexer.yytext;
              yylineno = lexer.yylineno;
              yyloc = lexer.yylloc;
              if (recovering > 0) {
                recovering--;
              }
            } else {
              symbol = preErrorSymbol;
              preErrorSymbol = null;
            }
            break;
          case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
              first_line: lstack[lstack.length - (len || 1)].first_line,
              last_line: lstack[lstack.length - 1].last_line,
              first_column: lstack[lstack.length - (len || 1)].first_column,
              last_column: lstack[lstack.length - 1].last_column,
            };
            if (ranges) {
              yyval._$.range = [
                lstack[lstack.length - (len || 1)].range[0],
                lstack[lstack.length - 1].range[1],
              ];
            }
            r = this.performAction.apply(
              yyval,
              [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack,
              ].concat(args),
            );
            if (typeof r !== "undefined") {
              return r;
            }
            if (len) {
              stack = stack.slice(0, -1 * len * 2);
              vstack = vstack.slice(0, -1 * len);
              lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
          case 3:
            return true;
        }
      }
      return true;
    },
  };

  /*
    Turtle / TriG / N-Triples / N-Quads parser in the Jison parser generator
    format — RDF 1.2, maintained by this project.

    Generated by `deno task parser:generate`; the runtime artifact
    (`turtle-generated.ts`) is pure ESM with zero runtime dependencies — term
    construction goes through the injected DataFactory (Parser.factory).

    The grammar mirrors the W3C RDF 1.2 TriG grammar (a superset of Turtle
    that also accepts N-Triples), extended with an N-Quads-style graph label
    on top-level statements so LOAD can ingest database-dump documents. The
    RDF 1.2 surface (triple terms, reifiers, annotation blocks) follows the
    spec's state-machine parsing semantics (TriG 5.3): reifiers and
    annotations emit `reifier rdf:reifies <<( s p o )>>` triples, and the
    node produced by a reified triple `<< s p o >>` is its reifier.
  */

  // State lives on statics so the generated module has no imports of its own:
  //   Parser.factory   — RDF/JS DataFactory (injected by the wrapper)
  //   Parser.base      — current base IRI (mutated by @base / BASE)
  //   Parser.prefixes  — { prefix: namespace } map (mutated by @prefix / PREFIX)
  //   Parser.quads     — output Quad[] (reset per parse)
  //   Parser._state    — { graph, subject, predicate, object, reifier,
  //                        tripleTerm, bnodeCounter, collectionStack,
  //                        pending, savedSubject, savedPredicate }

  var RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    RDF_TYPE = RDF + "type",
    RDF_FIRST = RDF + "first",
    RDF_REST = RDF + "rest",
    RDF_NIL = RDF + "nil",
    RDF_REIFIES = RDF + "reifies",
    XSD = "http://www.w3.org/2001/XMLSchema#",
    XSD_INTEGER = XSD + "integer",
    XSD_DECIMAL = XSD + "decimal",
    XSD_DOUBLE = XSD + "double",
    XSD_BOOLEAN = XSD + "boolean";

  function state() {
    return Parser._state;
  }

  function graphTerm() {
    return state().graph || Parser.factory.defaultGraph();
  }

  // Quads are buffered per statement and flushed by finishStatement so the
  // N-Quads graph label (which appears after the object list) can set the
  // graph before the quads are emitted.
  function emitQuad(s, p, o) {
    state().pending.push([s, p, o]);
  }

  function finishStatement() {
    var st = state();
    var g = graphTerm();
    for (var i = 0; i < st.pending.length; i++) {
      var q = st.pending[i];
      Parser.quads.push(Parser.factory.quad(q[0], q[1], q[2], g));
    }
    st.pending = [];
  }

  function freshBnode() {
    return Parser.factory.blankNode("b" + (++state().bnodeCounter));
  }

  function resolveIri(iri) {
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(iri)) return iri;
    if (!Parser.base) return iri;
    try {
      return new URL(iri, Parser.base).href;
    } catch (e) {
      return Parser.base + iri;
    }
  }

  function decodeUchar(m, u4, u8) {
    var cp = parseInt(u4 || u8, 16);
    if (cp >= 0xD800 && cp <= 0xDFFF) {
      throw new Error("Invalid Unicode escape (surrogate code point): " + m);
    }
    return String.fromCodePoint(cp);
  }

  function unescapeString(raw) {
    var quotes = /^'''|^\"\"\"|^'|^\"/.exec(raw)[0];
    var body = raw.slice(quotes.length, raw.length - quotes.length);
    return body
      .replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar)
      .replace(/\\([tbnrf"'\\])/g, function (m, ch) {
        return {
          t: "\t",
          b: "\b",
          n: "\n",
          r: "\r",
          f: "\f",
          '"': '"',
          "'": "'",
          "\\": "\\",
        }[ch];
      });
  }

  function unescapeIri(iri) {
    var result = iri.replace(
      /\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g,
      decodeUchar,
    );
    // IRIREF excludes U+0000-U+0020 and <>"{}|^`\\; an escape must not
    // smuggle any of them into the decoded IRI.
    if (/[\u0000-\u0020<>"{}|^`\\]/.test(result)) {
      throw new Error("Invalid IRI escape: disallowed character");
    }
    return result;
  }

  function resolvePrefixed(tok) {
    var i = tok.indexOf(":");
    var prefix = tok.slice(0, i);
    var ns = Parser.prefixes[prefix];
    if (ns == null) {
      throw new Error("Undefined prefix: " + prefix + ":");
    }
    // PN_LOCAL_ESC sequences (\_ \~ \. \- \! \$ \& \' \( \) \* \+ \, \; \= \/ \? \# \@ \%)
    // denote the literal character (TriG 4.5 PN_LOCAL_ESC); percent-escapes are kept as-is.
    return ns + tok.slice(i + 1).replace(/\\([_~.\-!$&'()*+,;=/?#@%])/g, "$1");
  }

  function addPrefix(pnameNs, iriTok) {
    var prefix = pnameNs.slice(0, -1);
    Parser.prefixes[prefix] = resolveIri(iriTok.slice(1, -1));
  }

  // --- RDF 1.2 reifier / annotation state machine (TriG 5.3.4-5.3.7) ---

  function startAnnotation() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.tripleTerm = Parser.factory.quad(st.subject, st.predicate, st.object);
    st.reifier = undefined;
  }

  function endAnnotation() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
  }

  function startAnnotationBlock() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    st.subject = st.reifier;
  }

  function endAnnotationBlock() {
    state().reifier = undefined;
  }

  function applyReifier(reifierTerm) {
    var st = state();
    st.reifier = reifierTerm || freshBnode();
    emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
  }

  // Finishing a reified triple (TriG 5.3.5): if no `~ reifier` was matched,
  // assign a fresh blank node; the reifying triple was already emitted by the
  // reifier production when a reifier was present. The node produced by the
  // production is the reifier.
  function nn(value) {
    return Parser.factory.namedNode(value);
  }

  function finishReifiedTriple() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    var node = st.reifier;
    st.reifier = undefined;
    return node;
  }

  // Emits the triple for a parsed object and prepares the annotation context
  // (TriG 5.3.3 / 5.3.6). Returns the object value.
  function emitObject(o) {
    state().object = o;
    emitQuad(state().subject, state().predicate, o);
    startAnnotation();
    return o;
  }

  // --- blank node property lists (TriG 5.3.8) ---

  function startBnpl() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.bnplNode = freshBnode();
    st.subject = st.bnplNode;
  }

  function endBnpl() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    return st.bnplNode;
  }

  // --- collections (TriG 5.3.9) ---

  function startCollection() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.collectionStack.push({ items: [] });
  }

  function collectionAdd(item) {
    state().collectionStack[state().collectionStack.length - 1].items.push(
      item,
    );
  }

  function endCollection() {
    var st = state();
    var coll = st.collectionStack.pop();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    var items = coll.items;
    if (items.length === 0) {
      return Parser.factory.namedNode(RDF_NIL);
    }
    var head = freshBnode();
    var cur = head;
    for (var i = 0; i < items.length; i++) {
      emitQuad(cur, nn(RDF_FIRST), items[i]);
      if (i < items.length - 1) {
        var next = freshBnode();
        emitQuad(cur, nn(RDF_REST), next);
        cur = next;
      } else {
        emitQuad(cur, nn(RDF_REST), nn(RDF_NIL));
      }
    }
    return head;
  }
  /* generated by jison-lex 0.3.4 */
  var lexer = (function () {
    var lexer = {
      EOF: 1,

      parseError: function parseError(str, hash) {
        if (this.yy.parser) {
          this.yy.parser.parseError(str, hash);
        } else {
          throw new Error(str);
        }
      },

      // resets the lexer, sets new input
      setInput: function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = "";
        this.conditionStack = ["INITIAL"];
        this.yylloc = {
          first_line: 1,
          first_column: 0,
          last_line: 1,
          last_column: 0,
        };
        if (this.options.ranges) {
          this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
      },

      // consumes and returns one char from the input
      input: function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno++;
          this.yylloc.last_line++;
        } else {
          this.yylloc.last_column++;
        }
        if (this.options.ranges) {
          this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
      },

      // unshifts one char (or a string) into the input
      unput: function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
          this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
          first_line: this.yylloc.first_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.first_column,
          last_column: lines
            ? (lines.length === oldLines.length
              ? this.yylloc.first_column
              : 0) +
              oldLines[oldLines.length - lines.length].length - lines[0].length
            : this.yylloc.first_column - len,
        };

        if (this.options.ranges) {
          this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
      },

      // When called from action, caches matched text and appends it on next action
      more: function () {
        this._more = true;
        return this;
      },

      // When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
      reject: function () {
        if (this.options.backtrack_lexer) {
          this._backtrack = true;
        } else {
          return this.parseError(
            "Lexical error on line " + (this.yylineno + 1) +
              ". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n" +
              this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            },
          );
        }
        return this;
      },

      // retain first n characters of the match
      less: function (n) {
        this.unput(this.match.slice(n));
      },

      // displays already matched input, i.e. for error messages
      pastInput: function () {
        var past = this.matched.substr(
          0,
          this.matched.length - this.match.length,
        );
        return (past.length > 20 ? "..." : "") +
          past.substr(-20).replace(/\n/g, "");
      },

      // displays upcoming input, i.e. for error messages
      upcomingInput: function () {
        var next = this.match;
        if (next.length < 20) {
          next += this._input.substr(0, 20 - next.length);
        }
        return (next.substr(0, 20) + (next.length > 20 ? "..." : "")).replace(
          /\n/g,
          "",
        );
      },

      // displays the character position where the lexing error occurred, i.e. for error messages
      showPosition: function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
      },

      // test the lexed token: return FALSE when not a match, otherwise return token
      test_match: function (match, indexed_rule) {
        var token,
          lines,
          backup;

        if (this.options.backtrack_lexer) {
          // save context
          backup = {
            yylineno: this.yylineno,
            yylloc: {
              first_line: this.yylloc.first_line,
              last_line: this.last_line,
              first_column: this.yylloc.first_column,
              last_column: this.yylloc.last_column,
            },
            yytext: this.yytext,
            match: this.match,
            matches: this.matches,
            matched: this.matched,
            yyleng: this.yyleng,
            offset: this.offset,
            _more: this._more,
            _input: this._input,
            yy: this.yy,
            conditionStack: this.conditionStack.slice(0),
            done: this.done,
          };
          if (this.options.ranges) {
            backup.yylloc.range = this.yylloc.range.slice(0);
          }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno += lines.length;
        }
        this.yylloc = {
          first_line: this.yylloc.last_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.last_column,
          last_column: lines
            ? lines[lines.length - 1].length -
              lines[lines.length - 1].match(/\r?\n?/)[0].length
            : this.yylloc.last_column + match[0].length,
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
          this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(
          this,
          this.yy,
          this,
          indexed_rule,
          this.conditionStack[this.conditionStack.length - 1],
        );
        if (this.done && this._input) {
          this.done = false;
        }
        if (token) {
          return token;
        } else if (this._backtrack) {
          // recover context
          for (var k in backup) {
            this[k] = backup[k];
          }
          return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
      },

      // return next match in input
      next: function () {
        if (this.done) {
          return this.EOF;
        }
        if (!this._input) {
          this.done = true;
        }

        var token,
          match,
          tempMatch,
          index;
        if (!this._more) {
          this.yytext = "";
          this.match = "";
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
          tempMatch = this._input.match(this.rules[rules[i]]);
          if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
            match = tempMatch;
            index = i;
            if (this.options.backtrack_lexer) {
              token = this.test_match(tempMatch, rules[i]);
              if (token !== false) {
                return token;
              } else if (this._backtrack) {
                match = false;
                continue; // rule action called reject() implying a rule MISmatch.
              } else {
                // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                return false;
              }
            } else if (!this.options.flex) {
              break;
            }
          }
        }
        if (match) {
          token = this.test_match(match, rules[index]);
          if (token !== false) {
            return token;
          }
          // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
          return false;
        }
        if (this._input === "") {
          return this.EOF;
        } else {
          return this.parseError(
            "Lexical error on line " + (this.yylineno + 1) +
              ". Unrecognized text.\n" + this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            },
          );
        }
      },

      // return next match that has a token
      lex: function lex() {
        var r = this.next();
        if (r) {
          return r;
        } else {
          return this.lex();
        }
      },

      // activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
      begin: function begin(condition) {
        this.conditionStack.push(condition);
      },

      // pop the previously active lexer condition state off the condition stack
      popState: function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
          return this.conditionStack.pop();
        } else {
          return this.conditionStack[0];
        }
      },

      // produce the lexer rule set which is active for the currently active lexer condition state
      _currentRules: function _currentRules() {
        if (
          this.conditionStack.length &&
          this.conditionStack[this.conditionStack.length - 1]
        ) {
          return this
            .conditions[this.conditionStack[this.conditionStack.length - 1]]
            .rules;
        } else {
          return this.conditions["INITIAL"].rules;
        }
      },

      // return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
      topState: function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
          return this.conditionStack[n];
        } else {
          return "INITIAL";
        }
      },

      // alias for begin(condition)
      pushState: function pushState(condition) {
        this.begin(condition);
      },

      // return the number of states currently on the stack
      stateStackSize: function stateStackSize() {
        return this.conditionStack.length;
      },
      options: { "flex": true },
      performAction: function anonymous(
        yy,
        yy_,
        $avoiding_name_collisions,
        YY_START,
      ) {
        var YYSTATE = YY_START;
        switch ($avoiding_name_collisions) {
          case 0: /* ignore */
            break;
          case 1:
            return 6;
            break;
          case 2:
            return 11;
            break;
          case 3:
            return 13;
            break;
          case 4:
            return 10;
            break;
          case 5:
            return 12;
            break;
          case 6:
            return 15;
            break;
          case 7:
            return 20;
            break;
          case 8:
            return 55;
            break;
          case 9:
            return 67;
            break;
          case 10:
            return 63;
            break;
          case 11:
            return 78;
            break;
          case 12:
            return 81;
            break;
          case 13:
            return 85;
            break;
          case 14:
            return 87;
            break;
          case 15:
            return 89;
            break;
          case 16:
            return 94;
            break;
          case 17:
            return 95;
            break;
          case 18:
            return 9;
            break;
          case 19:
            return 49;
            break;
          case 20:
            return 52;
            break;
          case 21:
            return 72;
            break;
          case 22:
            return 73;
            break;
          case 23:
            return 69;
            break;
          case 24:
            return 70;
            break;
          case 25:
            return 36;
            break;
          case 26:
            return 38;
            break;
          case 27:
            return 77;
            break;
          case 28:
            return 8;
            break;
          case 29:
            return 75;
            break;
          case 30:
            return 7;
            break;
          case 31:
            return 26;
            break;
          case 32:
            return 62;
            break;
          case 33:
            return 61;
            break;
          case 34:
            return 61;
            break;
          case 35:
            return 14;
            break;
          case 36:
            return 14;
            break;
          case 37:
            return 66;
            break;
          case 38:
            return 65;
            break;
          case 39:
            return 64;
            break;
          case 40:
            return "INVALID";
            break;
          case 41:
            console.log(yy_.yytext);
            break;
        }
      },
      rules: [
        /^(?:\s+|(#[^\n\r]*))/,
        /^(?:@prefix)/,
        /^(?:@base)/,
        /^(?:@version)/,
        /^(?:[Pp][Rr][Ee][Ff][Ii][Xx])/,
        /^(?:[Bb][Aa][Ss][Ee])/,
        /^(?:[Vv][Ee][Rr][Ss][Ii][Oo][Nn])/,
        /^(?:GRAPH)/,
        /^(?:a)/,
        /^(?:true|false)/,
        /^(?:\^\^)/,
        /^(?:<<\()/,
        /^(?:\)>>)/,
        /^(?:<<)/,
        /^(?:>>)/,
        /^(?:~)/,
        /^(?:\{\|)/,
        /^(?:\|\})/,
        /^(?:\.)/,
        /^(?:;)/,
        /^(?:,)/,
        /^(?:\()/,
        /^(?:\))/,
        /^(?:\[)/,
        /^(?:\])/,
        /^(?:\{)/,
        /^(?:\})/,
        /^(?:(\[\s*\]))/,
        /^(?:(<(?:[^<>\"{}|^`\\\u0000-\u0020]|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*>))/,
        /^(?:((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?)?:))((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|:|[0-9]|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%)))))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.|:|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%)))))*(((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|:|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%))))))?))))/,
        /^(?:((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?)?:)))/,
        /^(?:(_:(((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|[0-9])((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?))/,
        /^(?:(@[a-zA-Z]+(-[a-zA-Z0-9]+)*(--(ltr|rtl))?))/,
        /^(?:("""((("|"")?([^"\\]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f]))))*)"""))/,
        /^(?:('''((('|'')?([^'\\]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f]))))*)'''))/,
        /^(?:("([^\u0022\u005C\u000A\u000D]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*"))/,
        /^(?:('([^\u0027\u005C\u000A\u000D]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*'))/,
        /^(?:([+-]?(([0-9]+\.[0-9]*([eE][+-]?[0-9]+))|(\.[0-9]+([eE][+-]?[0-9]+))|([0-9]+([eE][+-]?[0-9]+)))))/,
        /^(?:([+-]?([0-9]*\.[0-9]+)))/,
        /^(?:([+-]?[0-9]+))/,
        /^(?:.)/,
        /^(?:.)/,
      ],
      conditions: {
        "INITIAL": {
          "rules": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
          ],
          "inclusive": true,
        },
      },
    };
    return lexer;
  })();
  parser.lexer = lexer;
  function Parser() {
    this.yy = {};
  }
  Parser.prototype = parser;
  parser.Parser = Parser;
  return new Parser();
})();
export default TurtleParser;
