// @ts-nocheck
// deno-lint-ignore-file
// Generated by `deno task parser:generate` — edit the .jison grammar instead.
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var TurtleParser = (function () {
  var o = function (k, v, o, l) {
      for (o = o || {}, l = k.length; l--; o[k[l]] = v);
      return o;
    },
    $V0 = [1, 6, 7, 8, 10, 11, 12, 13, 15, 20, 26, 36, 70, 73, 76, 78, 87],
    $V1 = [1, 33],
    $V2 = [1, 31],
    $V3 = [1, 34],
    $V4 = [1, 19],
    $V5 = [1, 37],
    $V6 = [1, 38],
    $V7 = [1, 32],
    $V8 = [1, 35],
    $V9 = [1, 36],
    $Va = [1, 51],
    $Vb = [7, 8, 55, 76],
    $Vc = [2, 13],
    $Vd = [7, 8, 9, 38, 55, 76],
    $Ve = [7, 8, 36, 55, 76],
    $Vf = [1, 88],
    $Vg = [1, 89],
    $Vh = [1, 90],
    $Vi = [1, 91],
    $Vj = [1, 92],
    $Vk = [1, 93],
    $Vl = [1, 87],
    $Vm = [
      7,
      8,
      9,
      14,
      26,
      36,
      38,
      49,
      52,
      55,
      62,
      65,
      66,
      67,
      68,
      70,
      71,
      73,
      74,
      76,
      78,
      79,
      82,
      87,
      89,
      91,
      96,
      97,
    ],
    $Vn = [7, 8, 14, 26, 62, 65, 66, 67, 68, 70, 73, 74, 76, 78, 79, 87],
    $Vo = [1, 101],
    $Vp = [7, 8, 14, 26, 62, 65, 66, 67, 68, 70, 73, 76, 78, 79, 87],
    $Vq = [9, 38],
    $Vr = [1, 120],
    $Vs = [1, 123],
    $Vt = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      55,
      62,
      65,
      66,
      67,
      68,
      70,
      71,
      73,
      74,
      76,
      78,
      79,
      87,
      91,
      96,
      97,
    ],
    $Vu = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      62,
      65,
      66,
      67,
      68,
      70,
      71,
      73,
      74,
      76,
      78,
      79,
      87,
      91,
      96,
      97,
    ],
    $Vv = [
      7,
      8,
      9,
      14,
      26,
      38,
      49,
      52,
      62,
      65,
      66,
      67,
      68,
      70,
      71,
      73,
      74,
      76,
      78,
      79,
      82,
      87,
      89,
      91,
      96,
      97,
    ],
    $Vw = [7, 8, 9, 26, 38, 49, 71, 76, 97],
    $Vx = [1, 137],
    $Vy = [7, 8, 9, 26, 38, 49, 52, 71, 76, 91, 96, 97],
    $Vz = [2, 127],
    $VA = [7, 8, 14, 26, 62, 65, 66, 67, 68, 76, 78, 79, 87],
    $VB = [7, 8, 9, 26, 38, 49, 52, 71, 76, 97],
    $VC = [7, 8, 9, 26, 38, 49, 52, 71, 76, 89, 91, 96, 97],
    $VD = [89, 91];
  var parser = {
    trace: function trace() {},
    yy: {},
    symbols_: {
      "error": 2,
      "document": 3,
      "document_repetition0": 4,
      "directive": 5,
      "PREFIX_ID": 6,
      "PNAME_NS": 7,
      "IRIREF": 8,
      ".": 9,
      "SPARQL_PREFIX": 10,
      "BASE_ID": 11,
      "SPARQL_BASE": 12,
      "VERSION_ID": 13,
      "STRING": 14,
      "SPARQL_VERSION": 15,
      "block": 16,
      "triplesOrGraph": 17,
      "wrappedGraph": 18,
      "triples2": 19,
      "GRAPH": 20,
      "graphLabelHeader": 21,
      "subjectHeader": 22,
      "labelOrSubject": 23,
      "setGraphLabel": 24,
      "iri": 25,
      "BLANK_NODE_LABEL": 26,
      "reifiedSubject": 27,
      "reifiedTriple": 28,
      "bnplSubject": 29,
      "blankNodePropertyList": 30,
      "predicateObjectList": 31,
      "triplesOrGraph_option0": 32,
      "triples2_option0": 33,
      "collectionSubject": 34,
      "collection": 35,
      "{": 36,
      "wrappedGraph_option0": 37,
      "}": 38,
      "triplesStatement": 39,
      "triples": 40,
      "triplesBlock": 41,
      "triplesBlock_option0": 42,
      "BlankNode": 43,
      "subject": 44,
      "triples_option0": 45,
      "triples_option1": 46,
      "verb": 47,
      "objectList": 48,
      ";": 49,
      "objectEmission": 50,
      "annotation": 51,
      ",": 52,
      "object": 53,
      "predicate": 54,
      "a": 55,
      "ttVerb": 56,
      "literal": 57,
      "tripleTerm": 58,
      "RDFLiteral": 59,
      "NumericLiteral": 60,
      "BooleanLiteral": 61,
      "STRING_LONG": 62,
      "LANG_DIR": 63,
      "^^": 64,
      "INTEGER": 65,
      "DECIMAL": 66,
      "DOUBLE": 67,
      "BOOLEAN": 68,
      "bnplStart": 69,
      "[": 70,
      "]": 71,
      "collectionStart": 72,
      "(": 73,
      ")": 74,
      "collectionItems": 75,
      "PNAME_LN": 76,
      "PrefixedName": 77,
      "ANON": 78,
      "<<(": 79,
      "ttSubject": 80,
      "ttObject": 81,
      ")>>": 82,
      "reifiedTripleBody": 83,
      "rtSubject": 84,
      "rtObject": 85,
      "reifiedTripleStart": 86,
      "<<": 87,
      "reifiedTriple_option0": 88,
      ">>": 89,
      "reifier": 90,
      "~": 91,
      "annotation_repetition0": 92,
      "annotationPart": 93,
      "annotationBlock": 94,
      "annotationBlockStart": 95,
      "{|": 96,
      "|}": 97,
      "document_repetition0_group0": 98,
      "triplesBlock_option0_option0": 99,
      "$accept": 0,
      "$end": 1,
    },
    terminals_: {
      2: "error",
      6: "PREFIX_ID",
      7: "PNAME_NS",
      8: "IRIREF",
      9: ".",
      10: "SPARQL_PREFIX",
      11: "BASE_ID",
      12: "SPARQL_BASE",
      13: "VERSION_ID",
      14: "STRING",
      15: "SPARQL_VERSION",
      20: "GRAPH",
      26: "BLANK_NODE_LABEL",
      36: "{",
      38: "}",
      49: ";",
      52: ",",
      55: "a",
      62: "STRING_LONG",
      63: "LANG_DIR",
      64: "^^",
      65: "INTEGER",
      66: "DECIMAL",
      67: "DOUBLE",
      68: "BOOLEAN",
      70: "[",
      71: "]",
      73: "(",
      74: ")",
      76: "PNAME_LN",
      78: "ANON",
      79: "<<(",
      82: ")>>",
      87: "<<",
      89: ">>",
      91: "~",
      96: "{|",
      97: "|}",
    },
    productions_: [
      0,
      [3, 1],
      [5, 4],
      [5, 3],
      [5, 3],
      [5, 2],
      [5, 3],
      [5, 2],
      [16, 1],
      [16, 1],
      [16, 1],
      [16, 3],
      [22, 1],
      [21, 1],
      [24, 1],
      [24, 1],
      [27, 1],
      [29, 1],
      [17, 2],
      [17, 3],
      [17, 4],
      [17, 3],
      [19, 3],
      [19, 3],
      [34, 1],
      [18, 3],
      [39, 1],
      [41, 2],
      [23, 1],
      [23, 1],
      [40, 2],
      [40, 2],
      [40, 2],
      [44, 1],
      [44, 1],
      [44, 1],
      [31, 2],
      [31, 4],
      [31, 2],
      [48, 2],
      [48, 4],
      [50, 1],
      [47, 1],
      [47, 1],
      [56, 1],
      [56, 1],
      [54, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [53, 1],
      [57, 1],
      [57, 1],
      [57, 1],
      [59, 1],
      [59, 1],
      [59, 2],
      [59, 2],
      [59, 3],
      [59, 3],
      [60, 1],
      [60, 1],
      [60, 1],
      [61, 1],
      [69, 1],
      [30, 3],
      [72, 1],
      [35, 2],
      [35, 3],
      [75, 1],
      [75, 2],
      [25, 1],
      [25, 1],
      [25, 1],
      [77, 1],
      [77, 1],
      [43, 1],
      [43, 1],
      [58, 5],
      [80, 1],
      [80, 1],
      [81, 1],
      [81, 1],
      [81, 1],
      [81, 1],
      [83, 3],
      [86, 1],
      [28, 4],
      [84, 1],
      [84, 1],
      [84, 1],
      [85, 1],
      [85, 1],
      [85, 1],
      [85, 1],
      [85, 1],
      [90, 1],
      [90, 2],
      [90, 2],
      [51, 1],
      [93, 1],
      [93, 1],
      [95, 1],
      [94, 3],
      [98, 1],
      [98, 1],
      [4, 0],
      [4, 2],
      [32, 0],
      [32, 1],
      [33, 0],
      [33, 1],
      [37, 0],
      [37, 1],
      [99, 0],
      [99, 1],
      [42, 0],
      [42, 2],
      [45, 0],
      [45, 1],
      [46, 0],
      [46, 1],
      [88, 0],
      [88, 1],
      [92, 0],
      [92, 2],
    ],
    performAction: function anonymous(
      yytext,
      yyleng,
      yylineno,
      yy,
      yystate, /* action[1] */
      $$, /* vstack */
      _$, /* lstack */
    ) {
      /* this == yyval */

      var $0 = $$.length - 1;
      switch (yystate) {
        case 2:
          this.$ = addPrefix($$[$0 - 2], $$[$0 - 1]);
          break;
        case 3:
          this.$ = addPrefix($$[$0 - 1], $$[$0]);
          break;
        case 4:
          this.$ = Parser.base = resolveIri($$[$0 - 1].slice(1, -1));
          break;
        case 5:
          this.$ = Parser.base = resolveIri($$[$0].slice(1, -1));
          break;
        case 11:
        case 18:
          this.$ = state().graph = undefined;
          break;
        case 12:
          this.$ = (state().subject = $$[$0], state().graph = undefined);
          break;
        case 13:
        case 14:
          this.$ = state().graph = $$[$0];
          break;
        case 15:
          this.$ = state().graph = Parser.factory.blankNode($$[$0].slice(2));
          break;
        case 16:
        case 17:
        case 24:
        case 33:
        case 34:
        case 35:
          this.$ = state().subject = $$[$0];
          break;
        case 19:
        case 21:
        case 22:
        case 23:
        case 26:
          this.$ = finishStatement();
          break;
        case 20:
          this.$ = (finishStatement(), state().graph = undefined);
          break;
        case 28:
        case 29:
        case 44:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
        case 55:
        case 56:
        case 77:
        case 78:
        case 82:
        case 83:
        case 84:
        case 85:
        case 86:
        case 87:
        case 91:
        case 92:
        case 93:
        case 94:
        case 95:
        case 96:
        case 97:
        case 98:
          this.$ = $$[$0];
          break;
        case 39:
        case 40:
          this.$ = endAnnotation();
          break;
        case 41:
          this.$ = emitObject($$[$0]);
          break;
        case 42:
          this.$ = state().predicate = $$[$0];
          break;
        case 43:
          this.$ = state().predicate = Parser.factory.namedNode(RDF_TYPE);
          break;
        case 45:
          this.$ = Parser.factory.namedNode(RDF_TYPE);
          break;
        case 57:
        case 58:
          this.$ = Parser.factory.literal(unescapeString($$[$0]));
          break;
        case 59:
        case 60:
          this.$ = Parser.factory.literal(
            unescapeString($$[$0 - 1]),
            langDirTag($$[$0].slice(1)),
          );
          break;
        case 61:
        case 62:
          this.$ = Parser.factory.literal(
            unescapeString($$[$0 - 2]),
            datatypeIri($$[$0]),
          );
          break;
        case 63:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_INTEGER),
          );
          break;
        case 64:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_DECIMAL),
          );
          break;
        case 65:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_DOUBLE),
          );
          break;
        case 66:
          this.$ = Parser.factory.literal(
            $$[$0],
            Parser.factory.namedNode(XSD_BOOLEAN),
          );
          break;
        case 67:
          this.$ = startBnpl();
          break;
        case 68:
          this.$ = endBnpl();
          break;
        case 69:
          this.$ = startCollection();
          break;
        case 70:
        case 71:
          this.$ = endCollection();
          break;
        case 72:
        case 73:
          this.$ = collectionAdd($$[$0]);
          break;
        case 74:
          this.$ = Parser.factory.namedNode(
            resolveIri(unescapeIri($$[$0].slice(1, -1))),
          );
          break;
        case 75:
        case 76:
          this.$ = Parser.factory.namedNode(resolvePrefixed($$[$0]));
          break;
        case 79:
          this.$ = Parser.factory.blankNode($$[$0].slice(2));
          break;
        case 80:
          this.$ = freshBnode();
          break;
        case 81:
          this.$ = Parser.factory.quad($$[$0 - 3], $$[$0 - 2], $$[$0 - 1]);
          break;
        case 88:
          this.$ = state().tripleTerm = Parser.factory.quad(
            $$[$0 - 2],
            $$[$0 - 1],
            $$[$0],
          );
          break;
        case 89:
          this.$ = startReifiedTriple();
          break;
        case 90:
          this.$ = finishReifiedTriple();
          break;
        case 99:
          this.$ = applyReifier(undefined);
          break;
        case 100:
        case 101:
          this.$ = applyReifier($$[$0]);
          break;
        case 105:
          this.$ = startAnnotationBlock();
          break;
        case 106:
          this.$ = endAnnotationBlock();
          break;
        case 109:
        case 127:
          this.$ = [];
          break;
        case 110:
        case 128:
          $$[$0 - 1].push($$[$0]);
          break;
      }
    },
    table: [
      o($V0, [2, 109], { 3: 1, 4: 2 }),
      { 1: [3] },
      {
        1: [2, 1],
        5: 4,
        6: [1, 6],
        7: $V1,
        8: $V2,
        10: [1, 7],
        11: [1, 8],
        12: [1, 9],
        13: [1, 10],
        15: [1, 11],
        16: 5,
        17: 12,
        18: 13,
        19: 14,
        20: [1, 15],
        21: 16,
        22: 17,
        23: 22,
        25: 26,
        26: $V3,
        27: 18,
        28: 23,
        29: 20,
        30: 24,
        34: 21,
        35: 25,
        36: $V4,
        43: 27,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        86: 28,
        87: $V9,
        98: 3,
      },
      o($V0, [2, 110]),
      o($V0, [2, 107]),
      o($V0, [2, 108]),
      { 7: [1, 39] },
      { 7: [1, 40] },
      { 8: [1, 41] },
      { 8: [1, 42] },
      { 14: [1, 43] },
      { 14: [1, 44] },
      o($V0, [2, 8]),
      o($V0, [2, 9]),
      o($V0, [2, 10]),
      {
        7: $V1,
        8: $V2,
        21: 45,
        23: 46,
        25: 26,
        26: $V3,
        43: 27,
        76: $V7,
        78: $V8,
      },
      { 18: 47, 36: $V4 },
      { 7: $V1, 8: $V2, 25: 52, 31: 48, 47: 49, 54: 50, 55: $Va, 76: $V7 },
      {
        7: $V1,
        8: $V2,
        9: [2, 111],
        25: 52,
        31: 54,
        32: 53,
        47: 49,
        54: 50,
        55: $Va,
        76: $V7,
      },
      {
        7: $V1,
        8: $V2,
        25: 62,
        26: $V3,
        27: 61,
        28: 23,
        29: 60,
        30: 24,
        35: 64,
        37: 55,
        38: [2, 115],
        39: 57,
        40: 58,
        41: 56,
        43: 63,
        44: 59,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        86: 28,
        87: $V9,
      },
      {
        7: $V1,
        8: $V2,
        9: [2, 113],
        25: 52,
        31: 66,
        33: 65,
        47: 49,
        54: 50,
        55: $Va,
        76: $V7,
      },
      { 7: $V1, 8: $V2, 25: 52, 31: 67, 47: 49, 54: 50, 55: $Va, 76: $V7 },
      o($Vb, [2, 12], { 36: $Vc }),
      o($Vd, [2, 16]),
      o($Vd, [2, 17]),
      o($Vb, [2, 24]),
      o($Ve, [2, 28]),
      o($Ve, [2, 29]),
      {
        7: $V1,
        8: $V2,
        25: 70,
        26: $V3,
        28: 72,
        43: 71,
        76: $V7,
        78: $V8,
        83: 68,
        84: 69,
        86: 28,
        87: $V9,
      },
      { 7: $V1, 8: $V2, 25: 52, 31: 73, 47: 49, 54: 50, 55: $Va, 76: $V7 },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 77,
        26: $V3,
        28: 83,
        30: 80,
        35: 79,
        43: 78,
        53: 76,
        57: 81,
        58: 82,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        74: [1, 74],
        75: 75,
        76: $V7,
        78: $V8,
        79: $Vl,
        86: 28,
        87: $V9,
      },
      o($Vm, [2, 74]),
      o($Vm, [2, 75]),
      o($Vm, [2, 76]),
      o($Vm, [2, 79]),
      o($Vm, [2, 80]),
      o([7, 8, 26, 76, 78, 87], [2, 89]),
      o($Vb, [2, 67]),
      o($Vn, [2, 69]),
      { 8: [1, 94] },
      { 8: [1, 95] },
      { 9: [1, 96] },
      o($V0, [2, 5]),
      { 9: [1, 97] },
      o($V0, [2, 7]),
      { 18: 98, 36: $V4 },
      { 36: $Vc },
      o($V0, [2, 18]),
      {
        7: $V1,
        8: $V2,
        9: [1, 99],
        24: 100,
        25: 102,
        26: [1, 103],
        49: $Vo,
        76: $V7,
      },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 77,
        26: $V3,
        28: 83,
        30: 80,
        35: 79,
        43: 78,
        48: 104,
        50: 105,
        53: 106,
        57: 81,
        58: 82,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        79: $Vl,
        86: 28,
        87: $V9,
      },
      o($Vp, [2, 42]),
      o($Vp, [2, 43]),
      o($Vp, [2, 46]),
      { 9: [1, 107] },
      { 9: [2, 112], 49: $Vo },
      { 38: [1, 108] },
      { 38: [2, 116] },
      { 9: [1, 110], 38: [2, 119], 42: 109 },
      o($Vq, [2, 26]),
      { 7: $V1, 8: $V2, 25: 52, 31: 111, 47: 49, 54: 50, 55: $Va, 76: $V7 },
      o($Vq, [2, 121], {
        47: 49,
        54: 50,
        25: 52,
        45: 112,
        31: 113,
        7: $V1,
        8: $V2,
        55: $Va,
        76: $V7,
      }),
      o($Vq, [2, 123], {
        47: 49,
        54: 50,
        25: 52,
        46: 114,
        31: 115,
        7: $V1,
        8: $V2,
        55: $Va,
        76: $V7,
      }),
      o($Vb, [2, 33]),
      o($Vb, [2, 34]),
      o($Vb, [2, 35]),
      { 9: [1, 116] },
      { 9: [2, 114], 49: $Vo },
      { 9: [1, 117], 49: $Vo },
      { 88: 118, 89: [2, 125], 90: 119, 91: $Vr },
      { 7: $V1, 8: $V2, 25: 52, 54: 122, 55: $Vs, 56: 121, 76: $V7 },
      o($Vb, [2, 91]),
      o($Vb, [2, 92]),
      o($Vb, [2, 93]),
      { 49: $Vo, 71: [1, 124] },
      o($Vt, [2, 70]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 77,
        26: $V3,
        28: 83,
        30: 80,
        35: 79,
        43: 78,
        53: 126,
        57: 81,
        58: 82,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        74: [1, 125],
        76: $V7,
        78: $V8,
        79: $Vl,
        86: 28,
        87: $V9,
      },
      o($Vn, [2, 72]),
      o($Vu, [2, 47]),
      o($Vu, [2, 48]),
      o($Vu, [2, 49]),
      o($Vu, [2, 50]),
      o($Vu, [2, 51]),
      o($Vu, [2, 52]),
      o($Vu, [2, 53]),
      o($Vv, [2, 54]),
      o($Vv, [2, 55]),
      o($Vv, [2, 56]),
      { 7: $V1, 8: $V2, 25: 128, 26: $V3, 43: 129, 76: $V7, 78: $V8, 80: 127 },
      o($Vv, [2, 57], { 63: [1, 130], 64: [1, 131] }),
      o($Vv, [2, 58], { 63: [1, 132], 64: [1, 133] }),
      o($Vv, [2, 63]),
      o($Vv, [2, 64]),
      o($Vv, [2, 65]),
      o($Vv, [2, 66]),
      { 9: [1, 134] },
      o($V0, [2, 3]),
      o($V0, [2, 4]),
      o($V0, [2, 6]),
      o($V0, [2, 11]),
      o($V0, [2, 19]),
      { 9: [1, 135] },
      o([9, 26, 38, 49, 71, 97], [2, 38], {
        54: 50,
        25: 52,
        47: 136,
        7: $V1,
        8: $V2,
        55: $Va,
        76: $V7,
      }),
      { 9: [2, 14] },
      { 9: [2, 15] },
      o($Vw, [2, 36], { 52: $Vx }),
      o($Vy, $Vz, { 51: 138, 92: 139 }),
      o($Vy, [2, 41]),
      o($V0, [2, 21]),
      o($V0, [2, 25]),
      { 38: [2, 27] },
      {
        7: $V1,
        8: $V2,
        25: 62,
        26: $V3,
        27: 61,
        28: 23,
        29: 60,
        30: 24,
        35: 64,
        38: [2, 117],
        39: 57,
        40: 58,
        41: 141,
        43: 63,
        44: 59,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        86: 28,
        87: $V9,
        99: 140,
      },
      o($Vq, [2, 30], { 49: $Vo }),
      o($Vq, [2, 31]),
      o($Vq, [2, 122], { 49: $Vo }),
      o($Vq, [2, 32]),
      o($Vq, [2, 124], { 49: $Vo }),
      o($V0, [2, 22]),
      o($V0, [2, 23]),
      { 89: [1, 142] },
      { 89: [2, 126] },
      o([9, 38, 49, 52, 71, 89, 91, 96, 97], [2, 99], {
        25: 143,
        43: 144,
        7: $V1,
        8: $V2,
        26: $V3,
        76: $V7,
        78: $V8,
      }),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 146,
        26: $V3,
        28: 150,
        43: 147,
        57: 148,
        58: 149,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        76: $V7,
        78: $V8,
        79: $Vl,
        85: 145,
        86: 28,
        87: $V9,
      },
      o($VA, [2, 44]),
      o($VA, [2, 45]),
      o($Vt, [2, 68]),
      o($Vt, [2, 71]),
      o($Vn, [2, 73]),
      { 7: $V1, 8: $V2, 25: 52, 54: 122, 55: $Vs, 56: 151, 76: $V7 },
      o($Vb, [2, 82]),
      o($Vb, [2, 83]),
      o($Vv, [2, 59]),
      { 7: $V1, 8: $V2, 25: 152, 76: $V7 },
      o($Vv, [2, 60]),
      { 7: $V1, 8: $V2, 25: 153, 76: $V7 },
      o($V0, [2, 2]),
      o($V0, [2, 20]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 77,
        26: $V3,
        28: 83,
        30: 80,
        35: 79,
        43: 78,
        48: 154,
        50: 105,
        53: 106,
        57: 81,
        58: 82,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        79: $Vl,
        86: 28,
        87: $V9,
      },
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 77,
        26: $V3,
        28: 83,
        30: 80,
        35: 79,
        43: 78,
        50: 155,
        53: 106,
        57: 81,
        58: 82,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        69: 29,
        70: $V5,
        72: 30,
        73: $V6,
        76: $V7,
        78: $V8,
        79: $Vl,
        86: 28,
        87: $V9,
      },
      o($VB, [2, 39]),
      o($VB, [2, 102], {
        93: 156,
        90: 157,
        94: 158,
        95: 159,
        91: $Vr,
        96: [1, 160],
      }),
      { 38: [2, 120] },
      { 38: [2, 118] },
      o([
        7,
        8,
        9,
        14,
        26,
        38,
        49,
        52,
        55,
        62,
        65,
        66,
        67,
        68,
        70,
        71,
        73,
        74,
        76,
        78,
        79,
        87,
        89,
        91,
        96,
        97,
      ], [2, 90]),
      o($VC, [2, 100]),
      o($VC, [2, 101]),
      o($VD, [2, 88]),
      o($VD, [2, 94]),
      o($VD, [2, 95]),
      o($VD, [2, 96]),
      o($VD, [2, 97]),
      o($VD, [2, 98]),
      {
        7: $V1,
        8: $V2,
        14: $Vf,
        25: 162,
        26: $V3,
        43: 163,
        57: 164,
        58: 165,
        59: 84,
        60: 85,
        61: 86,
        62: $Vg,
        65: $Vh,
        66: $Vi,
        67: $Vj,
        68: $Vk,
        76: $V7,
        78: $V8,
        79: $Vl,
        81: 161,
      },
      o($Vv, [2, 61]),
      o($Vv, [2, 62]),
      o($Vw, [2, 37], { 52: $Vx }),
      o($Vy, $Vz, { 92: 139, 51: 166 }),
      o($Vy, [2, 128]),
      o($Vy, [2, 103]),
      o($Vy, [2, 104]),
      { 7: $V1, 8: $V2, 25: 52, 31: 167, 47: 49, 54: 50, 55: $Va, 76: $V7 },
      o($Vb, [2, 105]),
      { 82: [1, 168] },
      { 82: [2, 84] },
      { 82: [2, 85] },
      { 82: [2, 86] },
      { 82: [2, 87] },
      o($VB, [2, 40]),
      { 49: $Vo, 97: [1, 169] },
      o($Vv, [2, 81]),
      o($Vy, [2, 106]),
    ],
    defaultActions: {
      46: [2, 13],
      56: [2, 116],
      102: [2, 14],
      103: [2, 15],
      109: [2, 27],
      119: [2, 126],
      140: [2, 120],
      141: [2, 118],
      162: [2, 84],
      163: [2, 85],
      164: [2, 86],
      165: [2, 87],
    },
    parseError: function parseError(str, hash) {
      if (hash.recoverable) {
        this.trace(str);
      } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
      }
    },
    parse: function parse(input) {
      var self = this,
        stack = [0],
        tstack = [],
        vstack = [null],
        lstack = [],
        table = this.table,
        yytext = "",
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;
      var args = lstack.slice.call(arguments, 1);
      var lexer = Object.create(this.lexer);
      var sharedState = { yy: {} };
      for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
          sharedState.yy[k] = this.yy[k];
        }
      }
      lexer.setInput(input, sharedState.yy);
      sharedState.yy.lexer = lexer;
      sharedState.yy.parser = this;
      if (typeof lexer.yylloc == "undefined") {
        lexer.yylloc = {};
      }
      var yyloc = lexer.yylloc;
      lstack.push(yyloc);
      var ranges = lexer.options && lexer.options.ranges;
      if (typeof sharedState.yy.parseError === "function") {
        this.parseError = sharedState.yy.parseError;
      } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
      }
      function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
      }
      _token_stack:
      var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        if (typeof token !== "number") {
          token = self.symbols_[token] || token;
        }
        return token;
      };
      var symbol,
        preErrorSymbol,
        state,
        action,
        a,
        r,
        yyval = {},
        p,
        len,
        newState,
        expected;
      while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
          action = this.defaultActions[state];
        } else {
          if (symbol === null || typeof symbol == "undefined") {
            symbol = lex();
          }
          action = table[state] && table[state][symbol];
        }
        if (typeof action === "undefined" || !action.length || !action[0]) {
          var errStr = "";
          expected = [];
          for (p in table[state]) {
            if (this.terminals_[p] && p > TERROR) {
              expected.push("'" + this.terminals_[p] + "'");
            }
          }
          if (lexer.showPosition) {
            errStr = "Parse error on line " + (yylineno + 1) + ":\n" +
              lexer.showPosition() + "\nExpecting " + expected.join(", ") +
              ", got '" + (this.terminals_[symbol] || symbol) + "'";
          } else {
            errStr = "Parse error on line " + (yylineno + 1) + ": Unexpected " +
              (symbol == EOF
                ? "end of input"
                : "'" + (this.terminals_[symbol] || symbol) + "'");
          }
          this.parseError(errStr, {
            text: lexer.match,
            token: this.terminals_[symbol] || symbol,
            line: lexer.yylineno,
            loc: yyloc,
            expected: expected,
          });
        }
        if (action[0] instanceof Array && action.length > 1) {
          throw new Error(
            "Parse Error: multiple actions possible at state: " + state +
              ", token: " + symbol,
          );
        }
        switch (action[0]) {
          case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
              yyleng = lexer.yyleng;
              yytext = lexer.yytext;
              yylineno = lexer.yylineno;
              yyloc = lexer.yylloc;
              if (recovering > 0) {
                recovering--;
              }
            } else {
              symbol = preErrorSymbol;
              preErrorSymbol = null;
            }
            break;
          case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
              first_line: lstack[lstack.length - (len || 1)].first_line,
              last_line: lstack[lstack.length - 1].last_line,
              first_column: lstack[lstack.length - (len || 1)].first_column,
              last_column: lstack[lstack.length - 1].last_column,
            };
            if (ranges) {
              yyval._$.range = [
                lstack[lstack.length - (len || 1)].range[0],
                lstack[lstack.length - 1].range[1],
              ];
            }
            r = this.performAction.apply(
              yyval,
              [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack,
              ].concat(args),
            );
            if (typeof r !== "undefined") {
              return r;
            }
            if (len) {
              stack = stack.slice(0, -1 * len * 2);
              vstack = vstack.slice(0, -1 * len);
              lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
          case 3:
            return true;
        }
      }
      return true;
    },
  };

  /*
    Turtle / TriG / N-Triples / N-Quads parser in the Jison parser generator
    format — RDF 1.2, maintained by this project.

    Generated by `deno task parser:generate`; the runtime artifact
    (`turtle-generated.ts`) is pure ESM with zero runtime dependencies — term
    construction goes through the injected DataFactory (Parser.factory).

    The grammar mirrors the W3C RDF 1.2 TriG grammar (a superset of Turtle
    that also accepts N-Triples), extended with an N-Quads-style graph label
    on top-level statements so LOAD can ingest database-dump documents. The
    RDF 1.2 surface (triple terms, reifiers, annotation blocks) follows the
    spec's state-machine parsing semantics (TriG 5.3): reifiers and
    annotations emit `reifier rdf:reifies <<( s p o )>>` triples, and the
    node produced by a reified triple `<< s p o >>` is its reifier.
  */

  // State lives on statics so the generated module has no imports of its own:
  //   Parser.factory   — RDF/JS DataFactory (injected by the wrapper)
  //   Parser.base      — current base IRI (mutated by @base / BASE)
  //   Parser.prefixes  — { prefix: namespace } map (mutated by @prefix / PREFIX)
  //   Parser.quads     — output Quad[] (reset per parse)
  //   Parser._state    — { graph, subject, predicate, object, reifier,
  //                        tripleTerm, bnodeCounter, collectionStack,
  //                        pending, savedSubject, savedPredicate }

  var RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    RDF_TYPE = RDF + "type",
    RDF_FIRST = RDF + "first",
    RDF_REST = RDF + "rest",
    RDF_NIL = RDF + "nil",
    RDF_REIFIES = RDF + "reifies",
    RDF_LANGSTRING = RDF + "langString",
    RDF_DIRLANGSTRING = RDF + "dirLangString",
    XSD = "http://www.w3.org/2001/XMLSchema#",
    XSD_INTEGER = XSD + "integer",
    XSD_DECIMAL = XSD + "decimal",
    XSD_DOUBLE = XSD + "double",
    XSD_BOOLEAN = XSD + "boolean";

  function state() {
    return Parser._state;
  }

  function graphTerm() {
    return state().graph || Parser.factory.defaultGraph();
  }

  // Quads are buffered per statement and flushed by finishStatement so the
  // N-Quads graph label (which appears after the object list) can set the
  // graph before the quads are emitted.
  function emitQuad(s, p, o) {
    state().pending.push([s, p, o]);
  }

  function finishStatement() {
    var st = state();
    var g = graphTerm();
    for (var i = 0; i < st.pending.length; i++) {
      var q = st.pending[i];
      Parser.quads.push(Parser.factory.quad(q[0], q[1], q[2], g));
    }
    st.pending = [];
  }

  function freshBnode() {
    return Parser.factory.blankNode("b" + (++state().bnodeCounter));
  }

  // --- RFC 3986 §5.2-5.3 relative-reference resolution ---
  // RDF 1.1 Turtle §6.3 (and RDF 1.2 Concepts) resolve relative IRIs with
  // the RFC 3986 algorithm, not WHATWG URL normalization. The two disagree on
  // edge cases such as a network-path reference with an empty path (`//host`,
  // which RFC 3986 recomposes to `scheme://host` with no trailing slash while
  // WHATWG appends "/"), so resolution is implemented from the RFC directly.

  // Splits a URI reference into its five RFC 3986 components.
  function parseUri3986(uri) {
    var m =
      /^(?:([^:\/?#]+):)?(?:\/\/([^\/?#]*))?([^?#]*)(?:\?([^#]*))?(?:#([\s\S]*))?$/
        .exec(uri);
    return {
      scheme: m[1],
      authority: m[2],
      path: m[3] || "",
      query: m[4],
      fragment: m[5],
    };
  }

  // RFC 3986 §5.2.4 remove_dot_segments.
  function removeDotSegments3986(path) {
    var input = path;
    var output = "";
    while (input.length > 0) {
      if (input.indexOf("../") === 0) {
        input = input.slice(3);
      } else if (input.indexOf("./") === 0) {
        input = input.slice(2);
      } else if (input.indexOf("/./") === 0) {
        input = "/" + input.slice(3);
      } else if (input === "/.") {
        input = "/";
      } else if (input.indexOf("/../") === 0) {
        input = "/" + input.slice(4);
        output = output.replace(/\/?[^\/]*$/, "");
      } else if (input === "/..") {
        input = "/";
        output = output.replace(/\/?[^\/]*$/, "");
      } else if (input === "." || input === "..") {
        input = "";
      } else {
        var seg = /^\/?[^\/]*/.exec(input)[0];
        output += seg;
        input = input.slice(seg.length);
      }
    }
    return output;
  }

  // RFC 3986 §5.2.3 merge (base path with a relative reference path).
  function mergePaths3986(base, refPath) {
    if (base.authority !== undefined && base.path === "") {
      return "/" + refPath;
    }
    return base.path.slice(0, base.path.lastIndexOf("/") + 1) + refPath;
  }

  // RFC 3986 §5.2.2 transform + §5.3 recomposition.
  function resolveRfc3986(base, ref) {
    var B = parseUri3986(base);
    var R = parseUri3986(ref);
    var T = {
      scheme: undefined,
      authority: undefined,
      path: "",
      query: undefined,
      fragment: undefined,
    };

    if (R.scheme !== undefined) {
      T.scheme = R.scheme;
      T.authority = R.authority;
      T.path = removeDotSegments3986(R.path);
      T.query = R.query;
    } else {
      if (R.authority !== undefined) {
        T.authority = R.authority;
        T.path = removeDotSegments3986(R.path);
        T.query = R.query;
      } else {
        if (R.path === "") {
          T.path = B.path;
          T.query = R.query !== undefined ? R.query : B.query;
        } else {
          T.path = R.path.charAt(0) === "/"
            ? removeDotSegments3986(R.path)
            : removeDotSegments3986(mergePaths3986(B, R.path));
          T.query = R.query;
        }
        T.authority = B.authority;
      }
      T.scheme = B.scheme;
    }
    T.fragment = R.fragment;

    var result = "";
    if (T.scheme !== undefined) result += T.scheme + ":";
    if (T.authority !== undefined) result += "//" + T.authority;
    result += T.path;
    if (T.query !== undefined) result += "?" + T.query;
    if (T.fragment !== undefined) result += "#" + T.fragment;
    return result;
  }

  function resolveIri(iri) {
    // An IRI that already has a scheme is already resolved (this also keeps
    // opaque-scheme IRIs such as urn: untouched).
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(iri)) return iri;
    if (!Parser.base) return iri;
    try {
      return resolveRfc3986(Parser.base, iri);
    } catch (e) {
      return Parser.base + iri;
    }
  }

  function decodeUchar(m, u4, u8) {
    var cp = parseInt(u4 || u8, 16);
    if (cp >= 0xD800 && cp <= 0xDFFF) {
      throw new Error("Invalid Unicode escape (surrogate code point): " + m);
    }
    return String.fromCodePoint(cp);
  }

  function unescapeString(raw) {
    var quotes = /^'''|^\"\"\"|^'|^\"/.exec(raw)[0];
    var body = raw.slice(quotes.length, raw.length - quotes.length);
    return body
      .replace(/\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g, decodeUchar)
      .replace(/\\([tbnrf"'\\])/g, function (m, ch) {
        return {
          t: "\t",
          b: "\b",
          n: "\n",
          r: "\r",
          f: "\f",
          '"': '"',
          "'": "'",
          "\\": "\\",
        }[ch];
      });
  }

  function unescapeIri(iri) {
    var result = iri.replace(
      /\\u([0-9A-Fa-f]{4})|\\U([0-9A-Fa-f]{8})/g,
      decodeUchar,
    );
    // IRIREF excludes U+0000-U+0020 and <>"{}|^`\\; an escape must not
    // smuggle any of them into the decoded IRI.
    if (/[\u0000-\u0020<>"{}|^`\\]/.test(result)) {
      throw new Error("Invalid IRI escape: disallowed character");
    }
    return result;
  }

  function resolvePrefixed(tok) {
    var i = tok.indexOf(":");
    var prefix = tok.slice(0, i);
    var ns = Parser.prefixes[prefix];
    if (ns == null) {
      throw new Error("Undefined prefix: " + prefix + ":");
    }
    // PN_LOCAL_ESC sequences (\_ \~ \. \- \! \$ \& \' \( \) \* \+ \, \; \= \/ \? \# \@ \%)
    // denote the literal character (TriG 4.5 PN_LOCAL_ESC); percent-escapes are kept as-is.
    return ns + tok.slice(i + 1).replace(/\\([_~.\-!$&'()*+,;=/?#@%])/g, "$1");
  }

  function addPrefix(pnameNs, iriTok) {
    var prefix = pnameNs.slice(0, -1);
    Parser.prefixes[prefix] = resolveIri(iriTok.slice(1, -1));
  }

  // --- RDF 1.2 literal well-formedness (Turtle 3.3 / N-Triples term
  //     constructors): language tags MUST be well-formed per BCP47
  //     (RFC 5646 section 2.2.9), and rdf:langString / rdf:dirLangString
  //     MUST NOT be written as explicit datatype IRIs. ---

  function isWellFormedBcp47(tag) {
    var ALPHA = /^[A-Za-z]+$/;
    var ALPHANUM = /^[A-Za-z0-9]+$/;
    var DIGIT = /^[0-9]+$/;
    // RFC 5646 section 2.2.8 grandfathered "irregular" tags, which do not
    // match the langtag ABNF but are nonetheless well-formed.
    var IRREGULAR = {
      "en-GB-oed": 1,
      "i-ami": 1,
      "i-bnn": 1,
      "i-default": 1,
      "i-enochian": 1,
      "i-hak": 1,
      "i-klingon": 1,
      "i-lux": 1,
      "i-mingo": 1,
      "i-navajo": 1,
      "i-pwn": 1,
      "i-tao": 1,
      "i-tay": 1,
      "i-tsu": 1,
      "sgn-BE-FR": 1,
      "sgn-BE-NL": 1,
      "sgn-CH-DE": 1,
    };
    if (Object.prototype.hasOwnProperty.call(IRREGULAR, tag)) return true;

    // privateuse = "x" 1*("-" 1*8alphanum)
    if (/^x(-[A-Za-z0-9]{1,8})+$/.test(tag)) return true;

    var subtags = tag.split("-");
    var i = 0;
    // language = 2*3ALPHA ["-" extlang] / 4ALPHA / 5*8ALPHA
    var lang = subtags[i++];
    if (lang.length >= 2 && lang.length <= 3) {
      if (!ALPHA.test(lang)) return false;
      // extlang = 3ALPHA *2("-" 3ALPHA)
      var extlangs = 0;
      while (
        i < subtags.length && extlangs < 3 &&
        subtags[i].length === 3 && ALPHA.test(subtags[i])
      ) {
        i++;
        extlangs++;
      }
    } else if (lang.length === 4) {
      if (!ALPHA.test(lang)) return false;
    } else if (lang.length >= 5 && lang.length <= 8) {
      if (!ALPHA.test(lang)) return false;
    } else {
      return false;
    }

    // script = 4ALPHA
    if (
      i < subtags.length && subtags[i].length === 4 &&
      ALPHA.test(subtags[i])
    ) {
      i++;
    }

    // region = 2ALPHA / 3DIGIT
    if (i < subtags.length) {
      var region = subtags[i];
      if (
        (region.length === 2 && ALPHA.test(region)) ||
        (region.length === 3 && DIGIT.test(region))
      ) {
        i++;
      }
    }

    // variant = 5*8alphanum / (DIGIT 3alphanum)
    while (i < subtags.length) {
      var variant = subtags[i];
      var isVariant = (variant.length >= 5 && variant.length <= 8 &&
        ALPHANUM.test(variant)) ||
        (variant.length === 4 && DIGIT.test(variant.charAt(0)) &&
          ALPHANUM.test(variant));
      if (!isVariant) break;
      i++;
    }

    // extension = singleton 1*("-" 2*8alphanum), where singleton is a single
    // alphanumeric other than x/X.
    while (i < subtags.length && /^[0-9A-WY-Za-wy-z]$/.test(subtags[i])) {
      i++;
      var extCount = 0;
      while (
        i < subtags.length && subtags[i].length >= 2 &&
        subtags[i].length <= 8 && ALPHANUM.test(subtags[i])
      ) {
        i++;
        extCount++;
      }
      if (extCount === 0) return false;
    }

    // privateuse = "x" 1*("-" 1*8alphanum)
    if (i < subtags.length && subtags[i] === "x") {
      i++;
      var puCount = 0;
      while (
        i < subtags.length && subtags[i].length >= 1 &&
        subtags[i].length <= 8 && ALPHANUM.test(subtags[i])
      ) {
        i++;
        puCount++;
      }
      if (puCount === 0) return false;
    }

    return i === subtags.length;
  }

  function langDirTag(langDir) {
    // langDir is the LANG_DIR token after its leading '@' (e.g. "en--ltr").
    // The optional "--ltr"/"--rtl" direction suffix is guaranteed by the
    // LANG_DIR terminal; validate only the language-tag portion.
    var dash = langDir.indexOf("--");
    var tag = dash === -1 ? langDir : langDir.slice(0, dash);
    if (!isWellFormedBcp47(tag)) {
      throw new Error("Language tag is not well-formed per BCP47: " + tag);
    }
    return langDir;
  }

  function datatypeIri(dt) {
    if (dt.value === RDF_LANGSTRING || dt.value === RDF_DIRLANGSTRING) {
      throw new Error(
        "rdf:langString and rdf:dirLangString must not be written as an explicit datatype IRI",
      );
    }
    return dt;
  }

  // --- RDF 1.2 reifier / annotation state machine (TriG 5.3.4-5.3.7) ---

  function startAnnotation() {
    var st = state();
    st.saveStack.push({
      subject: st.subject,
      predicate: st.predicate,
      tripleTerm: st.tripleTerm,
      reifier: st.reifier,
    });
    st.tripleTerm = Parser.factory.quad(st.subject, st.predicate, st.object);
    st.reifier = undefined;
  }

  function endAnnotation() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    st.tripleTerm = saved.tripleTerm;
    st.reifier = saved.reifier;
  }

  function startAnnotationBlock() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    st.subject = st.reifier;
  }

  function endAnnotationBlock() {
    state().reifier = undefined;
  }

  function applyReifier(reifierTerm) {
    var st = state();
    st.reifier = reifierTerm || freshBnode();
    emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
  }

  // Finishing a reified triple (TriG 5.3.5): if no `~ reifier` was matched,
  // assign a fresh blank node; the reifying triple was already emitted by the
  // reifier production when a reifier was present. The node produced by the
  // production is the reifier.
  function nn(value) {
    return Parser.factory.namedNode(value);
  }

  function startReifiedTriple() {
    var st = state();
    st.reifierStack.push({ reifier: st.reifier, tripleTerm: st.tripleTerm });
    st.reifier = undefined;
  }

  function finishReifiedTriple() {
    var st = state();
    if (!st.reifier) {
      st.reifier = freshBnode();
      emitQuad(st.reifier, nn(RDF_REIFIES), st.tripleTerm);
    }
    var node = st.reifier;
    var saved = st.reifierStack.pop();
    st.reifier = saved.reifier;
    st.tripleTerm = saved.tripleTerm;
    return node;
  }

  // Emits the triple for a parsed object and prepares the annotation context
  // (TriG 5.3.3 / 5.3.6). Returns the object value.
  function emitObject(o) {
    state().object = o;
    emitQuad(state().subject, state().predicate, o);
    startAnnotation();
    return o;
  }

  // --- blank node property lists (TriG 5.3.8) ---

  function startBnpl() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.bnplNode = freshBnode();
    st.subject = st.bnplNode;
  }

  function endBnpl() {
    var st = state();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    return st.bnplNode;
  }

  // --- collections (TriG 5.3.9) ---

  function startCollection() {
    var st = state();
    st.saveStack.push({ subject: st.subject, predicate: st.predicate });
    st.collectionStack.push({ items: [] });
  }

  function collectionAdd(item) {
    state().collectionStack[state().collectionStack.length - 1].items.push(
      item,
    );
  }

  function endCollection() {
    var st = state();
    var coll = st.collectionStack.pop();
    var saved = st.saveStack.pop();
    st.subject = saved.subject;
    st.predicate = saved.predicate;
    var items = coll.items;
    if (items.length === 0) {
      return Parser.factory.namedNode(RDF_NIL);
    }
    var head = freshBnode();
    var cur = head;
    for (var i = 0; i < items.length; i++) {
      emitQuad(cur, nn(RDF_FIRST), items[i]);
      if (i < items.length - 1) {
        var next = freshBnode();
        emitQuad(cur, nn(RDF_REST), next);
        cur = next;
      } else {
        emitQuad(cur, nn(RDF_REST), nn(RDF_NIL));
      }
    }
    return head;
  }
  /* generated by jison-lex 0.3.4 */
  var lexer = (function () {
    var lexer = {
      EOF: 1,

      parseError: function parseError(str, hash) {
        if (this.yy.parser) {
          this.yy.parser.parseError(str, hash);
        } else {
          throw new Error(str);
        }
      },

      // resets the lexer, sets new input
      setInput: function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = "";
        this.conditionStack = ["INITIAL"];
        this.yylloc = {
          first_line: 1,
          first_column: 0,
          last_line: 1,
          last_column: 0,
        };
        if (this.options.ranges) {
          this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
      },

      // consumes and returns one char from the input
      input: function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno++;
          this.yylloc.last_line++;
        } else {
          this.yylloc.last_column++;
        }
        if (this.options.ranges) {
          this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
      },

      // unshifts one char (or a string) into the input
      unput: function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
          this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
          first_line: this.yylloc.first_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.first_column,
          last_column: lines
            ? (lines.length === oldLines.length
              ? this.yylloc.first_column
              : 0) +
              oldLines[oldLines.length - lines.length].length - lines[0].length
            : this.yylloc.first_column - len,
        };

        if (this.options.ranges) {
          this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
      },

      // When called from action, caches matched text and appends it on next action
      more: function () {
        this._more = true;
        return this;
      },

      // When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
      reject: function () {
        if (this.options.backtrack_lexer) {
          this._backtrack = true;
        } else {
          return this.parseError(
            "Lexical error on line " + (this.yylineno + 1) +
              ". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n" +
              this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            },
          );
        }
        return this;
      },

      // retain first n characters of the match
      less: function (n) {
        this.unput(this.match.slice(n));
      },

      // displays already matched input, i.e. for error messages
      pastInput: function () {
        var past = this.matched.substr(
          0,
          this.matched.length - this.match.length,
        );
        return (past.length > 20 ? "..." : "") +
          past.substr(-20).replace(/\n/g, "");
      },

      // displays upcoming input, i.e. for error messages
      upcomingInput: function () {
        var next = this.match;
        if (next.length < 20) {
          next += this._input.substr(0, 20 - next.length);
        }
        return (next.substr(0, 20) + (next.length > 20 ? "..." : "")).replace(
          /\n/g,
          "",
        );
      },

      // displays the character position where the lexing error occurred, i.e. for error messages
      showPosition: function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
      },

      // test the lexed token: return FALSE when not a match, otherwise return token
      test_match: function (match, indexed_rule) {
        var token,
          lines,
          backup;

        if (this.options.backtrack_lexer) {
          // save context
          backup = {
            yylineno: this.yylineno,
            yylloc: {
              first_line: this.yylloc.first_line,
              last_line: this.last_line,
              first_column: this.yylloc.first_column,
              last_column: this.yylloc.last_column,
            },
            yytext: this.yytext,
            match: this.match,
            matches: this.matches,
            matched: this.matched,
            yyleng: this.yyleng,
            offset: this.offset,
            _more: this._more,
            _input: this._input,
            yy: this.yy,
            conditionStack: this.conditionStack.slice(0),
            done: this.done,
          };
          if (this.options.ranges) {
            backup.yylloc.range = this.yylloc.range.slice(0);
          }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno += lines.length;
        }
        this.yylloc = {
          first_line: this.yylloc.last_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.last_column,
          last_column: lines
            ? lines[lines.length - 1].length -
              lines[lines.length - 1].match(/\r?\n?/)[0].length
            : this.yylloc.last_column + match[0].length,
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
          this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(
          this,
          this.yy,
          this,
          indexed_rule,
          this.conditionStack[this.conditionStack.length - 1],
        );
        if (this.done && this._input) {
          this.done = false;
        }
        if (token) {
          return token;
        } else if (this._backtrack) {
          // recover context
          for (var k in backup) {
            this[k] = backup[k];
          }
          return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
      },

      // return next match in input
      next: function () {
        if (this.done) {
          return this.EOF;
        }
        if (!this._input) {
          this.done = true;
        }

        var token,
          match,
          tempMatch,
          index;
        if (!this._more) {
          this.yytext = "";
          this.match = "";
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
          tempMatch = this._input.match(this.rules[rules[i]]);
          if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
            match = tempMatch;
            index = i;
            if (this.options.backtrack_lexer) {
              token = this.test_match(tempMatch, rules[i]);
              if (token !== false) {
                return token;
              } else if (this._backtrack) {
                match = false;
                continue; // rule action called reject() implying a rule MISmatch.
              } else {
                // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                return false;
              }
            } else if (!this.options.flex) {
              break;
            }
          }
        }
        if (match) {
          token = this.test_match(match, rules[index]);
          if (token !== false) {
            return token;
          }
          // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
          return false;
        }
        if (this._input === "") {
          return this.EOF;
        } else {
          return this.parseError(
            "Lexical error on line " + (this.yylineno + 1) +
              ". Unrecognized text.\n" + this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            },
          );
        }
      },

      // return next match that has a token
      lex: function lex() {
        var r = this.next();
        if (r) {
          return r;
        } else {
          return this.lex();
        }
      },

      // activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
      begin: function begin(condition) {
        this.conditionStack.push(condition);
      },

      // pop the previously active lexer condition state off the condition stack
      popState: function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
          return this.conditionStack.pop();
        } else {
          return this.conditionStack[0];
        }
      },

      // produce the lexer rule set which is active for the currently active lexer condition state
      _currentRules: function _currentRules() {
        if (
          this.conditionStack.length &&
          this.conditionStack[this.conditionStack.length - 1]
        ) {
          return this
            .conditions[this.conditionStack[this.conditionStack.length - 1]]
            .rules;
        } else {
          return this.conditions["INITIAL"].rules;
        }
      },

      // return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
      topState: function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
          return this.conditionStack[n];
        } else {
          return "INITIAL";
        }
      },

      // alias for begin(condition)
      pushState: function pushState(condition) {
        this.begin(condition);
      },

      // return the number of states currently on the stack
      stateStackSize: function stateStackSize() {
        return this.conditionStack.length;
      },
      options: { "flex": true },
      performAction: function anonymous(
        yy,
        yy_,
        $avoiding_name_collisions,
        YY_START,
      ) {
        var YYSTATE = YY_START;
        switch ($avoiding_name_collisions) {
          case 0: /* ignore */
            break;
          case 1:
            return 6;
            break;
          case 2:
            return 11;
            break;
          case 3:
            return 13;
            break;
          case 4:
            return 10;
            break;
          case 5:
            return 12;
            break;
          case 6:
            return 15;
            break;
          case 7:
            return 20;
            break;
          case 8:
            return 55;
            break;
          case 9:
            return 68;
            break;
          case 10:
            return 64;
            break;
          case 11:
            return 79;
            break;
          case 12:
            return 82;
            break;
          case 13:
            return 87;
            break;
          case 14:
            return 89;
            break;
          case 15:
            return 91;
            break;
          case 16:
            return 96;
            break;
          case 17:
            return 97;
            break;
          case 18:
            return 9;
            break;
          case 19:
            return 49;
            break;
          case 20:
            return 52;
            break;
          case 21:
            return 73;
            break;
          case 22:
            return 74;
            break;
          case 23:
            return 70;
            break;
          case 24:
            return 71;
            break;
          case 25:
            return 36;
            break;
          case 26:
            return 38;
            break;
          case 27:
            return 78;
            break;
          case 28:
            return 8;
            break;
          case 29:
            return 76;
            break;
          case 30:
            return 7;
            break;
          case 31:
            return 26;
            break;
          case 32:
            return 63;
            break;
          case 33:
            return 62;
            break;
          case 34:
            return 62;
            break;
          case 35:
            return 14;
            break;
          case 36:
            return 14;
            break;
          case 37:
            return 67;
            break;
          case 38:
            return 66;
            break;
          case 39:
            return 65;
            break;
          case 40:
            return "INVALID";
            break;
          case 41:
            console.log(yy_.yytext);
            break;
        }
      },
      rules: [
        /^(?:\s+|(#[^\n\r]*))/,
        /^(?:@prefix)/,
        /^(?:@base)/,
        /^(?:@version)/,
        /^(?:[Pp][Rr][Ee][Ff][Ii][Xx])/,
        /^(?:[Bb][Aa][Ss][Ee])/,
        /^(?:[Vv][Ee][Rr][Ss][Ii][Oo][Nn])/,
        /^(?:GRAPH)/,
        /^(?:a)/,
        /^(?:true|false)/,
        /^(?:\^\^)/,
        /^(?:<<\()/,
        /^(?:\)>>)/,
        /^(?:<<)/,
        /^(?:>>)/,
        /^(?:~)/,
        /^(?:\{\|)/,
        /^(?:\|\})/,
        /^(?:\.)/,
        /^(?:;)/,
        /^(?:,)/,
        /^(?:\()/,
        /^(?:\))/,
        /^(?:\[)/,
        /^(?:\])/,
        /^(?:\{)/,
        /^(?:\})/,
        /^(?:(\[\s*\]))/,
        /^(?:(<(?:[^<>\"{}|^`\\\u0000-\u0020]|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*>))/,
        /^(?:((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?)?:))((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|:|[0-9]|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%)))))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.|:|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%)))))*(((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|:|(((%[0-9A-Fa-f]{2})|(\\(_|~|\.|-|!|\$|&|'|\(|\)|\*|\+|,|;|=|\/|\?|#|@|%))))))?))))/,
        /^(?:((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF]))((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?)?:)))/,
        /^(?:(_:(((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|[0-9])((((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040]))|\.)*((((([A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]|[\uD800-\uDB7F][\uDC00-\uDFFF])|_))|-|[0-9]|\u00B7|[\u0300-\u036F\u203F-\u2040])))?))/,
        /^(?:(@[a-zA-Z]+(-[a-zA-Z0-9]+)*(--(ltr|rtl))?))/,
        /^(?:("""((("|"")?([^"\\]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f]))))*)"""))/,
        /^(?:('''((('|'')?([^'\\]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f]))))*)'''))/,
        /^(?:("([^\u0022\u005C\u000A\u000D]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*"))/,
        /^(?:('([^\u0027\u005C\u000A\u000D]|(\\[tbnrf"'\\])|(\\u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|\\U([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])))*'))/,
        /^(?:([+-]?(([0-9]+\.[0-9]*([eE][+-]?[0-9]+))|(\.[0-9]+([eE][+-]?[0-9]+))|([0-9]+([eE][+-]?[0-9]+)))))/,
        /^(?:([+-]?([0-9]*\.[0-9]+)))/,
        /^(?:([+-]?[0-9]+))/,
        /^(?:.)/,
        /^(?:.)/,
      ],
      conditions: {
        "INITIAL": {
          "rules": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
          ],
          "inclusive": true,
        },
      },
    };
    return lexer;
  })();
  parser.lexer = lexer;
  function Parser() {
    this.yy = {};
  }
  Parser.prototype = parser;
  parser.Parser = Parser;
  return new Parser();
})();
export default TurtleParser;
